"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar" | "zh" | "ko" | "ur";

// High-quality translations for all pages, divisions, and components
const translations: Record<Language, any> = {
  en: {
    navbar: {
      home: "Home",
      about: "About Us",
      machinery: "Heavy Machinery",
      parts: "Spare Parts",
      hardware: "Industrial Hardware",
      contact: "Contact",
      getInTouch: "Get In Touch",
      announcement: "SIAL GLOBAL | Global Industrial Sourcing Ecosystem — Factory-Direct Heavy Machinery, YSIT® Automotive Parts & SADAAN® Hardware Supplies.",
    },
    footer: {
      divisions: "Divisions",
      platforms: "Our Platforms",
      operations: "Global Operations",
      contacts: "Corporate Contacts",
      centralEmail: "Central Email",
      wechat: "WeChat Enterprise ID",
      governance: "Multi-jurisdictional governance assured.",
      ceoMessage: "CEO's Message",
      b2bInquiry: "B2B Inquiry routing",
    },
    home: {
      legacyBadge: "🛡️ 18-Year Global Governance Legacy",
      heroTitle: "Multi-Jurisdictional Industrial Trading &",
      heroHighlight: "Infrastructure Procurement",
      heroDesc: "As an elite multinational enterprise, SIAL Group drives industrial trade excellence across global corridors. Our capabilities combine heavy construction machinery sales and crane rentals with wholesale genuine automotive parts export and A-to-Z construction site hardware procurement. By connecting direct East Asian production lines with high-demand markets in the GCC and Africa, we guarantee tier-1 quality control, supply chain resilience, and global logistics efficiency.",
      routeInquiry: "Route B2B Inquiry",
      ceoBio: "Group Biography",
      explore: "Explore",
      edgeTitle: "Our Competitive Edge: ",
      edgeHighlight: "Factory-Direct Sourcing & Zero Broker Margins",
      edgeDesc: "Unlike traditional trading brokers who inflate costs with layers of intermediary markups, SIAL Group operates proprietary, factory-direct sourcing hubs at key global economic crossroads. By controlling our own international procurement networks, we guarantee direct factory pricing, absolute supply chain visibility, and premium quality assurance for global enterprises.",
      koreaTitle: "Strategic Automotive Sourcing HQ",
      koreaEntity: "Entity: SIAL & Young A Trading Co.",
      koreaDesc: "Operating a B2B integration node with top-tier automotive and heavy machinery component manufacturers. We specialize in the high-volume export of wholesale genuine automotive spare parts (Hyundai, Kia, and commercial fleets) directly from Korean production lines to global markets, eliminating middleman fees.",
      chinaTitle: "Premier Industrial Hardware Node",
      chinaEntity: "Entity: Yiwu SIAL International Trading Co. Ltd.",
      chinaDesc: "Managing an elite, large-scale industrial procurement and infrastructure logistics network. This hub drives the direct sourcing of A-to-Z industrial hardware, heavy-duty power tools, and high-volume construction site equipment, optimized for direct bulk shipping and seamless distribution into Africa and the GCC.",
      whyChooseTitle: "Why Global Partners Choose SIAL Group",
      whyChoose1Title: "Direct Factory Pricing",
      whyChoose1Desc: "100% elimination of third-party trading broker margins and hidden intermediary fees.",
      whyChoose2Title: "Strict Quality Assurance",
      whyChoose2Desc: "End-to-end quality control and pre-shipment inspections performed directly at the manufacturer level.",
      whyChoose3Title: "Unmatched Supply Chain Resilience",
      whyChoose3Desc: "Seamless multi-jurisdictional logistics and secure global distribution networks operating under robust corporate governance.",
      whyChoose4Title: "18+ Years of B2B Trade Expertise",
      whyChoose4Desc: "Decades of cross-border trade negotiation, international procurement excellence, and multinational supply chain management.",
      ceoMessageTitle: "Message from our Group CEO",
      ceoSubtitle: "Muhammad Amjad: A Legacy of Supply Chain Resilience",
      ceoDesc1: "Under the leadership of Muhammad Amjad, SIAL Group has spent nearly two decades transforming from a localized trading agent into a multi-jurisdictional industrial force. By establishing direct factory pipelines and shipping routes from South Korea and China to the GCC and Africa, he has set a new benchmark for supply chain independence.",
      ceoDesc2: "His strategic focus combines strict adherence to regional compliance protocols (such as SASO in Saudi Arabia, OPAL in Oman, and Maputo port customs operations) with B2B logistics negotiation, guaranteeing direct pricing benefits for our enterprise partners.",
      ceoConsultation: "Schedule B2B Consultation",
      divisionsTitle: "Our Enterprise Divisions",
      divisionsSubtitle: "Explore our integrated divisions driving growth and resilience across the GCC, Africa, and East Asia.",
      machineryTitle: "Heavy Machinery Division",
      machineryDesc: "Sales, crane fleet rentals, and spare parts distribution across Oman (SK Transports), Saudi Arabia (SIAL International Company), and Pakistan imports.",
      partsTitle: "Automotive Spare Parts",
      partsDesc: "High-volume replacement spare parts for Hyundai and Kia models, sourced directly from South Korea and Yiwu, China networks.",
      hardwareTitle: "Industrial Hardware",
      hardwareDesc: "Infrastructure development distribution in Mozambique, providing high-quality construction materials sourced directly from our China nodes.",
      stats1: "Years Legacy",
      stats2: "Global Hubs",
      stats3: "Middleman Margins",
      stats4: "Quality Inspected",
    },
    about: {
      whoWeAre: "Who We Are",
      title: "18 Years of Multi-Jurisdictional Governance",
      desc: "For nearly two decades, SIAL Group has stood as a pioneer of multi-jurisdictional governance and cross-border supply chain optimization. Strategically headquartered with active hubs in South Korea, China, Oman, Saudi Arabia, and East Africa, our operations bridge major global industrial centers with emerging markets. Guided by CEO Muhammad Amjad’s rigorous commitment to trade compliance, high-level diplomatic negotiation, and factory-direct procurement, the Group ensures unparalleled supply chain resilience in heavy lifting machinery sales, genuine Kia and Hyundai automotive parts, and bulk industrial hardware. Our transparent corporate governance framework guarantees seamless international compliance, securing trusted partnerships with regional distributors, state-owned enterprises, and private commercial fleets worldwide.",
      ceoProfileTitle: "Executive Leadership Profile",
      ceoProfileHeading: "Muhammad Amjad: A Legacy of Supply Chain Vision",
      ceoQuote: "Resilience is not merely surviving supply chain blockades; it is building proprietary pipelines that ensure our partners never fail.",
      ceoDelegate: "🏛️ GCC & East Asia Trade Delegate",
      ceoDesc1: "Muhammad Amjad, the Group CEO and Founder, established SIAL Group with the target of building direct, high-trust cross-border relationships. Recognizing early on that middleman margins eroded supply chain efficiency, he spent nearly two decades creating direct sourcing networks.",
      ceoDesc2: "His international trade negotiation expertise is backed by a robust legal and governance framework. His operations span multiple jurisdictions, allowing SIAL Group to seamlessly navigate trade compliance, import duties, and customs protocols across South Korea, China, the GCC (Oman and Saudi Arabia), and Africa (Mozambique).",
      ceoDesc3: "To support these operations and optimize client-facing delivery, SIAL Group hosts specialized online platforms, including SK Transports Oman for heavy machinery fleet operations, and both Sial Kingdom and Yahya Auto Parts for automotive spare parts sourcing and mechanical services.",
      focusAreas: "Focus Areas",
      focusValue: "Cross-Border Tariffs & Compliance",
      strategicHubs: "Strategic Hubs",
      strategicValue: "Seoul, Yiwu, Muscat, Jeddah",
      pillarsTitle: "Enterprise Core",
      pillarsHeading: "Corporate Capabilities",
      pillar1Title: "Global Supply Chain Resilience",
      pillar1Desc: "By maintaining ownership of procurement hubs in China and Korea, SIAL Group guarantees stock availability and shields customers from sudden maritime logjams and geopolitical supply shocks.",
      pillar2Title: "Trade Negotiation Expertise",
      pillar2Desc: "Our CEO's direct relationships with international port authorities and shipping lines allow for expedited clearance and highly favorable freight arrangements.",
      pillar3Title: "Multi-Jurisdictional Governance",
      pillar3Desc: "Strict adherence to regional corporate compliance laws, including SASO in Saudi Arabia, OPAL in Oman, and customs clearing protocols in Mozambique and South Asia.",
      networkTitle: "Enterprise Footprint",
      networkHeading: "Our Global Corporate Network",
      networkDesc: "SIAL Group operates across multiple international jurisdictions. Filter our 10 registered subsidiaries, logistics pipelines, and direct sourcing hubs.",
    },
    machinery: {
      titleBadge: "Division Profiling",
      heading: "Heavy Machinery & Fleet Logistics",
      subtitle: "Providing heavy lift mobile cranes, construction vehicles, and heavy-duty spare parts. Our division operates across three key regional hubs under strict quality assurance.",
      omanBadge: "🇴🇲 Oman Operations",
      omanTitle: "GCC Leadership in Mobile Crane Sales & Rentals",
      omanDesc: "For over a decade, SK Transports Oman has been the gold standard for heavy lifting solutions in the Sultanate of Oman. Specializing in high-capacity truck-mounted cranes, mobile telescopic cranes, and crawler cranes, we serve major oil & gas pipelines, marine cargo projects, and urban infrastructure developments.",
      omanFeature1: "✓ 25 to 500 Ton Lift Capacity",
      omanFeature2: "✓ OPAL Certified Operators",
      omanFeature3: "✓ 24/7 Site Support",
      omanCta: "Visit SK Transports Oman Site ↗",
      fleetTitle: "Active Fleet Portfolio Showcase",
      fleetBadge: "PDO Approved Fleet",
      saBadge: "🇸🇦 Saudi Arabia Expansion",
      saTitle: "Newly Launched Rental Fleet & Heavy Spare Parts",
      saDesc: "Expanding SIAL's footprint into Jeddah and the Eastern Province to support the massive Vision 2030 development pipelines. SIAL International Company offers truck mobile cranes sales, long-term fleet rentals, and high-quality heavy spare parts distribution.",
      saFeature1: "Direct parts replacement from South Korea networks",
      saFeature2: "Mobile crane maintenance and rigging services",
      saFeature3: "Compliance with SASO & Saudi oil-field safety standards",
      saCta: "Request Quote for Saudi",
      pkBadge: "🇵🇰 Pakistan Operations",
      pkTitle: "East Asian Procurement Node & Regional Import",
      pkDesc: "Large-scale import and regional distribution of high-performance construction machinery and specialized agricultural equipment. Sourced directly from our East Asian networks, we eliminate third-party margins to supply heavy machinery directly to Pakistani contractors and farming enterprises.",
      pkFeature1: "Crawler tractors and harvest loaders",
      pkFeature2: "Specialized agricultural seeding machinery",
      pkFeature3: "Direct import from South Korea and Yiwu procurement hubs",
      pkCta: "Inquire Pakistan Imports",
    },
    parts: {
      badge: "Automotive Division",
      heading: "Genuine Replacement Spare Parts",
      subtitle: "High-volume distribution channels supplying new and used genuine spare parts for Korean passenger and commercial vehicles. Directly integrated with OEM manufacturers and verified exporters.",
      specBadge: "Core Specialization",
      specHeading: "Unrivaled Supply of Hyundai & Kia Components",
      specDesc: "We specialize in new and used genuine replacement parts for all major Hyundai and Kia models. Our volume distribution channels cater to GCC warehouse distributors, large-scale commercial fleets, and national retail chains. By bypassing multiple broker channels, we secure high-turnover components directly from origin.",
      cat1Title: "Engine & Drivetrain",
      cat1Desc: "Full engines, gearboxes, pistons, and transmission components.",
      cat2Title: "Suspension & Steering",
      cat2Desc: "Shock absorbers, linkages, control arms, and steering racks.",
      cat3Title: "Electrical & Body Panels",
      cat3Desc: "Alternators, ECUs, headlamps, bumpers, and body moldings.",
      cat4Title: "High-Wear Consumables",
      cat4Desc: "Brake assemblies, filtration systems, spark plugs, and gaskets.",
      infraHeading: "GCC Distribution Infrastructure",
      infraOmanTitle: "Oman Hub (Sial Kingdom Trading LLC)",
      infraOmanDesc: "Sial Kingdom Trading LLC, our primary customer-facing platform in Seeb, Muscat, coordinates local fleet operations and genuine spare parts distribution across the Sultanate.",
      infraSaTitle: "Saudi Arabia Expansion",
      infraSaDesc: "Replicating our successful Oman framework, our Jeddah-based operations now distribute high-volume spare parts to retailers and corporate transit fleets throughout Saudi Arabia's major economic corridors.",
      hubsBadge: "Active Customer Platforms",
      hubsHeading: "Our Automotive Spare Parts & Service Hubs",
      hubsDesc: "SIAL Group operates two prominent customer-facing brands in the Sultanate of Oman, providing factory-direct parts and expert repair services.",
      skBadge: "Oman Seeb Division",
      skTitle: "Sial Kingdom Trading LLC",
      skDesc: "Sial Kingdom is a trusted auto services workshop and genuine spare parts dealer located in the Ma’abilah Industrial Area (Sanaiya), Seeb, Oman. Specializing in Kia and Hyundai vehicles, they offer everything from routine diagnostics to advanced mechanical and body repairs with direct-factory replacement components.",
      skCta: "Explore Sial Kingdom Site ↗",
      yahyaBadge: "Global Logistics Hub",
      yahyaTitle: "Yahya Auto Parts",
      yahyaDesc: "Founded in 2006, Yahya Auto Parts (Yahya Bin Khalfan LLC) has grown into a leading wholesale and retail distributor of genuine Hyundai, Kia, and Genesis spare parts in Oman, with shipping and procurement operations spanning South Korea, China, and Pakistan.",
      yahyaCta: "Explore Yahya Auto Parts Site ↗",
      integrityHeading: "Direct Sourcing Integrity",
      integrityDesc: "Ensuring genuine quality from factory to fleet via our proprietary procurement nodes.",
      sourcingKorea: "Our primary East Asian procurement node based in Seoul, South Korea. We coordinate directly with manufacturing hubs and authorized OEM channels to secure new parts, while inspecting and certifying used spare parts directly on-site before shipping container loadouts.",
      sourcingChina: "Located in Yiwu, the global wholesale trade capital. This hub conducts meticulous quality audits and oversees export logistics of industrial-grade replacements, ensuring that every shipment meets strict international quality criteria.",
      erpTitle: "Real-Time ERP Tracking",
      erpDesc: "Leveraging our customized Odoo ERP dashboard to monitor warehouse logistics, direct-factory orders, transit shipping paths, and regional compliance audits in real-time across GCC and African corridors.",
    },
    hardware: {
      badge: "Industrial Division",
      heading: "Industrial Hardware & Construction Materials",
      subtitle: "Facilitating the import, clearance, and distribution of high-strength structural materials. Connecting large-scale infrastructure developments in East Africa with direct production sources.",
      mzBadge: "🇲🇿 Africa Pipelines",
      mzTitle: "Supporting Mozambique's Strategic Infrastructure Pipelines",
      mzDesc: "As Mozambique undergoes massive development in mining, gas logistics, and transport corridors, SIAL Group provides the physical foundation. We import and distribute bulk industrial hardware, structural steels, high-tensile fasteners, and safety gear. Through our regional clearing agents in Maputo and Beira, we manage the entire import workflow from container discharge to on-site project storage.",
      cat1Title: "Structural Materials",
      cat1Desc: "Rebars, structural beams, wire meshes, and formwork solutions.",
      cat2Title: "Fasteners & Rigging",
      cat2Desc: "High-tensile bolts, anchors, shackles, wire ropes, and hoisting tackle.",
      cat3Title: "Site Safety & Piping",
      cat3Desc: "Steel pipes, valves, specialized safety gear, and industrial tools.",
      integrityTitle: "Supply Integrity Status",
      routeTitle: "Shipping Route:",
      routeVal: "Ningbo ➔ Maputo Port",
      clearTitle: "Clearance Time:",
      clearVal: "Under 7 Days",
      qualityTitle: "Quality Assured:",
      qualityVal: "100% Certified",
      reachTitle: "Distribution Reach:",
      reachVal: "Maputo, Beira, Nacala",
      procBadge: "Procurement Integration",
      procHeading: "Seamless Integration with Yiwu Sourcing Node",
      procTitle: "China Sourcing Node",
      proc1Title: "Direct Factory Linkages",
      proc1Desc: "Direct partnership with leading steel mills and tool factories in Zhejiang and Jiangsu provinces.",
      proc2Title: "Bulk Price Advantage",
      proc2Desc: "Procuring large volumes directly from sources eliminates multi-layered broker commission markups.",
      proc3Title: "Custom Fabrication",
      proc3Desc: "Assuring structural steel can be pre-cut, pre-drilled, and fabricated to custom blueprints.",
      procDesc: "SIAL Group's procurement node in China coordinates the entire manufacturing, loading, and inspection pipeline. We conduct physical thickness audits, tension loading tests, and coating checks on all construction materials before sealing container locks. This direct pipeline protects African projects from sub-standard materials and excessive broker costs.",
      cta: "Submit Bulk Material RFQ",
    },
    contact: {
      badge: "Inquiry Desk",
      heading: "B2B Communication Routing",
      desc: "Connect directly with our multi-jurisdictional divisions. Select your target market or division to route your RFQ directly to the appropriate regional head office.",
      formTitle: "B2B Inquiry Routing Portal",
      formDesc: "Select division and destination hub to ensure immediate routing to the relevant director.",
      companyName: "Corporate Entity Name",
      contactName: "Primary Contact Name",
      email: "Corporate Email Address",
      phone: "Direct Phone Number (include country code)",
      division: "Target Division",
      selectDiv: "Select Target Division",
      destHub: "Destination Operations Hub",
      selectHub: "Select Destination Hub",
      details: "Detailed Scope of Inquiry & RFQ Specifications",
      placeholderDetails: "Please provide dimensions, volume, shipping destination, and expected delivery timeline...",
      submitting: "Routing RFQ...",
      submit: "Submit B2B Inquiry",
      successTitle: "Inquiry Successfully Routed",
      successDesc: "Your RFQ has been logged and routed to the corresponding regional head office. A division director will contact you via email shortly.",
      errTitle: "Submission Error",
      errDesc: "Could not route inquiry. Please verify network connectivity and try again.",
      infoTitle: "Corporate Coordinates",
      hqTitle: "Global Headquarters",
      hqVal: "Muscat, Sultanate of Oman",
      emailTitle: "Central Corporate Email",
      wechatTitle: "WeChat Enterprise ID",
      workTitle: "Operational Core Hours",
      workVal: "08:00 - 17:00 (GMT+4) | Monday - Friday",
    }
  },
  ar: {
    navbar: {
      home: "الرئيسية",
      about: "من نحن",
      machinery: "الآليات الثقيلة",
      parts: "قطع الغيار",
      hardware: "المعدات الصناعية",
      contact: "اتصل بنا",
      getInTouch: "تواصل معنا",
      announcement: "سيال العالمية | منظومة التوريد الصناعي العالمي — آليات ثقيلة مباشرة من المصنع، قطع غيار سيارات ®YSIT ومعدات ®SADAAN الصناعية.",
    },
    footer: {
      divisions: "الأقسام",
      platforms: "منصاتنا",
      operations: "العمليات العالمية",
      contacts: "الاتصالات المؤسسية",
      centralEmail: "البريد الإلكتروني المركزي",
      wechat: "معرف WeChat للمؤسسة",
      governance: "الحوكمة متعددة الولايات القضائية مضمونة.",
      ceoMessage: "رسالة الرئيس التنفيذي",
      b2bInquiry: "توجيه استفسارات B2B",
    },
    home: {
      legacyBadge: "🛡️ إرث حوكمة عالمي يمتد لـ 18 عامًا",
      heroTitle: "التجارة الصناعية متعددة الولايات و",
      heroHighlight: "تأمين البنية التحتية",
      heroDesc: "بصفتها مؤسسة رائدة متعددة الجنسيات، تقود مجموعة سيال (SIAL Group) التميز في التجارة الصناعية عبر الممرات العالمية. تجمع قدراتنا بين مبيعات آليات الإنشاءات الثقيلة وتأجير الرافعات مع تصدير قطع غيار السيارات الأصلية بالجملة وتأمين المعدات الصناعية لمواقع البناء من الألف إلى الياء. من خلال ربط خطوط الإنتاج المباشرة في شرق آسيا بالأسواق ذات الطلب المرتفع في دول مجلس التعاون الخليجي وأفريقيا، نضمن التحكم الفائق في الجودة، ومرونة سلاسل التوريد، وكفاءة الخدمات اللوجستية العالمية.",
      routeInquiry: "توجيه استفسار B2B",
      ceoBio: "السيرة الذاتية للمجموعة",
      explore: "استكشف",
      edgeTitle: "ميزتنا التنافسية: ",
      edgeHighlight: "التوريد المباشر من المصنع وبدون هوامش وسطاء",
      edgeDesc: "على عكس وسطاء التجارة التقليديين الذين يرفعون التكاليف بهوامش متعددة، تدير مجموعة سيال مراكز توريد مملوكة ومباشرة من المصانع في تقاطعات اقتصادية عالمية رئيسية. من خلال التحكم في شبكات المشتريات الدولية الخاصة بنا، نضمن أسعار المصنع المباشرة، والرؤية المطلقة لسلسلة التوريد، وضمان الجودة الفائقة للمؤسسات العالمية.",
      koreaTitle: "المقر الاستراتيجي لتوريد قطع غيار السيارات",
      koreaEntity: "الكيان: شركة سيال و يونغ إيه للتجارة",
      koreaDesc: "تشغيل مركز تكامل B2B مع كبار مصنعي قطع غيار السيارات ومكونات الآليات الثقيلة. نحن متخصصون في التصدير بكميات كبيرة لقطع غيار السيارات الأصلية بالجملة (هيونداي، كيا، والأساطيل التجارية) مباشرة من خطوط الإنتاج الكورية إلى الأسواق العالمية، مما يلغي رسوم الوسطاء.",
      chinaTitle: "المركز الرئيسي للمعدات الصناعية",
      chinaEntity: "الكيان: شركة إيو سيال للتجارة الدولية المحدودة",
      chinaDesc: "إدارة شبكة مشتريات صناعية وخدمات لوجستية للبنية التحتية واسعة النطاق. يقود هذا المركز التوريد المباشر للمعدات الصناعية من الألف إلى الياء، والأدوات الكهربائية الشاقة، ومعدات مواقع البناء بكميات كبيرة، والمحسنة للشحن المباشر والتوزيع السلس إلى أفريقيا ودول مجلس التعاون الخليجي.",
      whyChooseTitle: "لماذا يختار الشركاء العالميون مجموعة سيال؟",
      whyChoose1Title: "أسعار مباشرة من المصنع",
      whyChoose1Desc: "إلغاء 100٪ لهوامش وسطاء التجارة والرسوم المخفية.",
      whyChoose2Title: "ضمان جودة صارم",
      whyChoose2Desc: "مراقبة الجودة وفحوصات ما قبل الشحن التي يتم إجراؤها مباشرة على مستوى المصنع.",
      whyChoose3Title: "مرونة سلسلة توريد لا مثيل لها",
      whyChoose3Desc: "خدمات لوجستية سلسة وشبكات توزيع عالمية آمنة تعمل تحت حوكمة مؤسسية قوية.",
      whyChoose4Title: "أكثر من 18 عامًا من الخبرة في تجارة B2B",
      whyChoose4Desc: "عقود من الخبرة في مفاوضات التجارة العابرة للحدود، والتميز في المشتريات الدولية، وإدارة سلاسل التوريد متعددة الجنسيات.",
      ceoMessageTitle: "رسالة من الرئيس التنفيذي للمجموعة",
      ceoSubtitle: "محمد أمجد: إرث من مرونة سلاسل التوريد",
      ceoDesc1: "تحت قيادة محمد أمجد، قضت مجموعة سيال قرابة عقدين من الزمن في التحول من وكيل تجاري محلي إلى قوة صناعية متعددة الولايات القضائية. من خلال إنشاء خطوط إمداد مباشرة من المصانع وطرق شحن من كوريا الجنوبية والصين إلى دول مجلس التعاون الخليجي وأفريقيا، وضع معيارًا جديدًا لاستقلال سلاسل التوريد.",
      ceoDesc2: "يجمع تركيزه الاستراتيجي بين الالتزام الصارم ببروتوكولات الامتثال الإقليمية (مثل SASO في المملكة العربية السعودية، و OPAL في عمان، وعمليات جمارك ميناء مابوتو) مع مفاوضات الخدمات اللوجستية B2B، مما يضمن مزايا التسعير المباشر لشركائنا من المؤسسات.",
      ceoConsultation: "جدولة استشارة B2B",
      divisionsTitle: "أقسام المؤسسة",
      divisionsSubtitle: "استكشف أقسامنا المتكاملة التي تدفع النمو والمرونة عبر دول مجلس التعاون الخليجي وأفريقيا وشرق آسيا.",
      machineryTitle: "قسم الآليات الثقيلة",
      machineryDesc: "المبيعات وتأجير أساطيل الرافعات وتوزيع قطع الغيار في عمان (إس كي للنقل) والمملكة العربية السعودية (شركة سيال الدولية) وواردات باكستان.",
      partsTitle: "قطع غيار السيارات",
      partsDesc: "توزيع قطع الغيار البديلة الأصلية بكميات كبيرة لموديلات هيونداي وكيا، المستوردة مباشرة من شبكات كوريا الجنوبية وإيو بالصين.",
      hardwareTitle: "المعدات الصناعية",
      hardwareDesc: "توزيع تطوير البنية التحتية في موزمبيق، وتوفير مواد بناء عالية الجودة يتم توريدها مباشرة من مراكزنا في الصين.",
      stats1: "سنوات الإرث",
      stats2: "المراكز العالمية",
      stats3: "هوامش الوسطاء",
      stats4: "فحص الجودة",
    },
    about: {
      whoWeAre: "من نحن",
      title: "18 عامًا من الحوكمة متعددة الولايات",
      desc: "لقرابة عقدين من الزمن، وقفت مجموعة سيال كشركة رائدة في الحوكمة متعددة الولايات وتحسين سلاسل التوريد العابرة للحدود. من خلال مقرنا الاستراتيجي ومراكزنا النشطة في كوريا الجنوبية والصين وعمان والمملكة العربية السعودية وشرق أفريقيا، تجسر عملياتنا المراكز الصناعية العالمية الرئيسية بالأسواق الناشئة. بتوجيه من الرئيس التنفيذي محمد أمجد والتزامه الصارم بالامتثال التجاري، والمفاوضات الدبلوماسية رفيعة المستوى، والمشتريات المباشرة من المصانع، تضمن المجموعة مرونة لا مثيل لها في مبيعات آليات الرفع الثقيلة، وقطع غيار سيارات كيا وهيونداي الأصلية، والمعدات الصناعية بالجملة. يضمن إطار حوكمة الشركات الشفاف لدينا امتثالاً دوليًا سلسًا، مما يؤمن شراكات موثوقة مع الموزعين الإقليميين، والشركات المملوكة للدولة، والأساطيل التجارية الخاصة في جميع أنحاء العالم.",
      ceoProfileTitle: "ملف القيادة التنفيذية",
      ceoProfileHeading: "محمد أمجد: مسيرة من الرؤية لسلاسل التوريد",
      ceoQuote: "المرونة ليست مجرد البقاء على قيد الحياة بعد حصار سلاسل التوريد؛ بل هي بناء خطوط إمداد مملوكة تضمن عدم فشل شركائنا أبدًا.",
      ceoDelegate: "🏛️ مندوب تجاري لدول مجلس التعاون الخليجي وشرق آسيا",
      ceoDesc1: "أسس محمد أمجد، الرئيس التنفيذي ومؤسس المجموعة، مجموعة سيال بهدف بناء علاقات مباشرة وعالية الثقة عابرة للحدود. وإدراكًا منه مبكرًا لكون هوامش الوسطاء تقوض كفاءة سلسلة التوريد، فقد أمضى ما يقرب من عقدين من الزمن في إنشاء شبكات توريد مباشرة.",
      ceoDesc2: "تعتمد خبرته في مفاوضات التجارة الدولية على إطار قانوني وإداري قوي. وتغطي عملياته ولايات قضائية متعددة، مما يسمح لمجموعة سيال بالتنقل بسلاسة في الامتثال التجاري ورسوم الاستيراد وبروتوكولات الجمارك في كوريا الجنوبية والصين ودول مجلس التعاون الخليجي (عمان والمملكة العربية السعودية) وأفريقيا (موزمبيق).",
      ceoDesc3: "لدعم هذه العمليات وتحسين تسليم الخدمات للعملاء، تدير مجموعة سيال منصات متخصصة عبر الإنترنت، بما في ذلك SK Transports Oman لعمليات أسطول الآليات الثقيلة، وكل من Sial Kingdom و Yahya Auto Parts لتوريد قطع غيار السيارات والخدمات الميكانيكية.",
      focusAreas: "مجالات التركيز",
      focusValue: "التعريفات الجمركية والامتثال عابر الحدود",
      strategicHubs: "المراكز الاستراتيجية",
      strategicValue: "سيول، إيو، مسقط، جدة",
      pillarsTitle: "جوهر المؤسسة",
      pillarsHeading: "القدرات المؤسسية",
      pillar1Title: "مرونة سلسلة التوريد العالمية",
      pillar1Desc: "من خلال الحفاظ على ملكية مراكز المشتريات في الصين وكوريا، تضمن مجموعة سيال توفر المخزون وتحمي العملاء من الاختناقات البحرية المفاجئة وصدمات الإمداد الجيوسياسية.",
      pillar2Title: "الخبرة في مفاوضات التجارة",
      pillar2Desc: "تتيح علاقات رئيسنا التنفيذي المباشرة مع سلطات الموانئ الدولية وخطوط الشحن إمكانية التخليص السريع وترتيبات شحن مناسبة للغاية.",
      pillar3Title: "الحوكمة متعددة الولايات",
      pillar3Desc: "الالتزام الصارم بقوانين امتثال الشركات الإقليمية، بما في ذلك SASO في المملكة العربية السعودية، و OPAL في عمان، وبروتوكولات التخليص الجمركي في موزمبيق وجنوب آسيا.",
      networkTitle: "البصمة المؤسسية",
      networkHeading: "شبكتنا المؤسسية العالمية",
      networkDesc: "تعمل مجموعة سيال عبر ولايات قضائية دولية متعددة. قم بتصفية شركاتنا الفرعية العشر المسجلة، وخطوطنا اللوجستية، ومراكز التوريد المباشرة لدينا.",
    },
    machinery: {
      titleBadge: "توصيف القسم",
      heading: "الآليات الثقيلة ولوجستيات الأسطول",
      subtitle: "توفير الرافعات المتنقلة ذات الحمولة الثقيلة، ومركبات الإنشاءات، وقطع غيار المعدات الثقيلة. يعمل قسمنا عبر ثلاثة مراكز إقليمية رئيسية تحت ضمان جودة صارم.",
      omanBadge: "🇴🇲 عمليات سلطنة عمان",
      omanTitle: "الريادة الخليجية في مبيعات وتأجير الرافعات المتنقلة",
      omanDesc: "لأكثر من عقد من الزمان، كانت شركة إس كي للنقل (SK Transports Oman) هي المعيار الذهبي لحلول الرفع الثقيل في سلطنة عمان. متخصصون في الرافعات الشاحنة ذات السعة العالية، والرافعات التلسكوبية المتنقلة، والرافعات الجنزيرية، نخدم خطوط أنابيب النفط والغاز الكبرى، ومشاريع الشحن البحري، وتطوير البنية التحتية الحضرية.",
      omanFeature1: "✓ قدرة رفع من 25 إلى 500 طن",
      omanFeature2: "✓ مشغلون معتمدون من OPAL",
      omanFeature3: "✓ دعم للموقع على مدار الساعة 24/7",
      omanCta: "زيارة موقع إس كي للنقل عمان ↗",
      fleetTitle: "عرض محفظة الأسطول النشط",
      fleetBadge: "أسطول معتمد من PDO",
      saBadge: "🇸🇦 التوسع في المملكة العربية السعودية",
      saTitle: "أسطول الإيجار الجديد وقطع الغيار الثقيلة",
      saDesc: "توسيع حضور سيال في جدة والمنطقة الشرقية لدعم مشاريع رؤية 2030 الضخمة. تقدم شركة سيال الدولية مبيعات الرافعات الشاحنة المتنقلة، وتأجير الأساطيل طويل الأجل، وتوزيع قطع غيار الآليات الثقيلة عالية الجودة.",
      saFeature1: "استبدال مباشر لقطع الغيار من شبكات كوريا الجنوبية",
      saFeature2: "خدمات صيانة الرافعات المتنقلة والتجهيز",
      saFeature3: "الالتزام بمعايير السلامة SASO ومعايير حقول النفط السعودية",
      saCta: "طلب عرض أسعار للسعودية",
      pkBadge: "🇵🇰 عمليات باكستان",
      pkTitle: "مركز مشتريات شرق آسيا والاستيراد الإقليمي",
      pkDesc: "استيراد وتوزيع إقليمي واسع النطاق لآليات الإنشاءات عالية الأداء والمعدات الزراعية المتخصصة. يتم توريدها مباشرة من شبكاتنا في شرق آسيا، حيث نلغي هوامش الطرف الثالث لتوريد الآليات الثقيلة مباشرة للمقاولين والمؤسسات الزراعية في باكستان.",
      pkFeature1: "الجرارات الجنزيرية وحاصدات التحميل",
      pkFeature2: "آلات بذر البذور الزراعية المتخصصة",
      pkFeature3: "استيراد مباشر من مراكز المشتريات في كوريا الجنوبية وإيو",
      pkCta: "استعلام عن واردات باكستان",
    },
    parts: {
      badge: "قسم السيارات",
      heading: "قطع غيار بديلة أصلية",
      subtitle: "قنوات توزيع عالية الحجم توفر قطع غيار أصلية جديدة ومستعملة للسيارات الكورية السياحية والتجارية. متكاملة مباشرة مع المصنعين الأصليين والمصدرين المعتمدين.",
      specBadge: "التخصص الأساسي",
      specHeading: "توريد لا مثيل له لمكونات هيونداي وكيا",
      specDesc: "نحن متخصصون في قطع الغيار البديلة الأصلية الجديدة والمستعملة لجميع موديلات هيونداي وكيا الرئيسية. تلبي قنوات التوزيع الكبيرة لدينا احتياجات موزعي المستودعات في الخليج، وأساطيل النقل التجارية الضخمة، وسلاسل التجزئة الوطنية. من خلال تجاوز قنوات الوسطاء المتعددة، نؤمن المكونات عالية الطلب مباشرة من المنشأ.",
      cat1Title: "المحرك ونظام الحركة",
      cat1Desc: "المحركات الكاملة، وعلب التروس، والمكابس، ومكونات ناقل الحركة.",
      cat2Title: "التعليق والتوجيه",
      cat2Desc: "ممتصات الصدمات، والوصلات، وأذرع التحكم، وعلب التوجيه.",
      cat3Title: "الكهرباء وألواح الهيكل",
      cat3Desc: "المولدات، ووحدات التحكم الإلكترونية (ECU)، والمصابيح الأمامية، والمصدات، وقوالب الهيكل.",
      cat4Title: "المواد الاستهلاكية السريعة التلف",
      cat4Desc: "مجموعات الفرامل، وأنظمة الفلترة، وشمعات الاحتراق (البواجي)، والحواشي (الكازكيت).",
      infraHeading: "البنية التحتية للتوزيع في الخليج",
      infraOmanTitle: "مركز عمان (شركة سيال كينجدوم للتجارة ش.م.م)",
      infraOmanDesc: "تعد شركة سيال كينجدوم للتجارة ش.م.م، منصتنا الرئيسية للخدمات وتوزيع قطع الغيار الأصلية في السيب بمسقط، حيث تخدم الأساطيل ومحلات التجزئة بتوريد موثوق وسريع.",
      infraSaTitle: "التوسع في المملكة العربية السعودية",
      infraSaDesc: "استمرارًا لإطار عملنا الناجح في عمان، تقوم عملياتنا في جدة الآن بتوزيع قطع الغيار بكميات كبيرة لتجار التجزئة وأساطيل النقل للشركات عبر الممرات الاقتصادية الرئيسية في المملكة العربية السعودية.",
      hubsBadge: "منصات العملاء النشطة",
      hubsHeading: "مراكز قطع غيار السيارات والخدمات التابعة لنا",
      hubsDesc: "تدير مجموعة سيال علامتين تجاريتين بارزتين موجهتين للعملاء في سلطنة عمان، وتقدمان قطع غيار مباشرة من المصنع وخدمات إصلاح خبيرة.",
      skBadge: "فرع السيب بسلطنة عمان",
      skTitle: "شركة سيال كينجدوم للتجارة ش.م.م",
      skDesc: "سيال كينجدوم هي ورشة خدمات سيارات وموزع قطع غيار أصلية موثوق به يقع في منطقة المعبيلة الصناعية (الصناعية)، السيب، عمان. متخصصون في سيارات كيا وهيونداي، ويقدمون كل شيء بدءًا من التشخيص الروتيني إلى الإصلاحات الميكانيكية وإصلاحات الهيكل المتقدمة باستخدام قطع غيار بديلة مباشرة من المصنع.",
      skCta: "اكتشف موقع سيال كينجدوم ↗",
      yahyaBadge: "المركز اللوجستي العالمي",
      yahyaTitle: "يحيى لقطع غيار السيارات",
      yahyaDesc: "تأسست يحيى لقطع غيار السيارات (شركة يحيى بن خلفان ش.م.م) في عام 2006، ونمت لتصبح موزعًا رائدًا بالجملة والتجزئة لقطع غيار هيونداي وكيا وجينيسيس الأصلية في عمان، مع عمليات شحن ومشتريات تمتد عبر كوريا الجنوبية والصين وباكستان.",
      yahyaCta: "اكتشف موقع يحيى لقطع الغيار ↗",
      integrityHeading: "نزاهة التوريد المباشر",
      integrityDesc: "ضمان الجودة الأصلية من المصنع إلى الأسطول عبر مراكز المشتريات الخاصة بنا.",
      sourcingKorea: "مركز المشتريات الرئيسي في شرق آسيا ومقره سيول، كوريا الجنوبية. ننسق مباشرة مع مصانع التصنيع والقنوات المعتمدة للمصنعين الأصليين لتأمين القطع الجديدة، مع فحص واعتماد قطع الغيار المستعملة مباشرة في الموقع قبل تحميل الحاويات وشحنها.",
      sourcingChina: "يقع في مدينة إيو، عاصمة التجارة بالجملة العالمية. يجري هذا المركز عمليات تدقيق دقيقة للجودة ويشرف على لوجستيات التصدير للبدائل الصناعية، مع ضمان تلبية كل شحنة لمعايير الجودة الدولية الصارمة.",
      erpTitle: "تتبع ERP في الوقت الحقيقي",
      erpDesc: "الاستفادة من لوحة معلومات Odoo ERP المخصصة لمراقبة لوجستيات المستودعات، وطلبات المصانع المباشرة، ومسارات الشحن العابرة، وعمليات تدقيق الامتثال الإقليمية في الوقت الحقيقي عبر الممرات الخليجية والأفريقية.",
    },
    hardware: {
      badge: "القسم الصناعي",
      heading: "المعدات الصناعية ومواد البناء",
      subtitle: "تسهيل استيراد وتخليص وتوزيع المواد الإنشائية عالية القوة. ربط مشاريع البنية التحتية واسعة النطاق في شرق أفريقيا بمصادر الإنتاج المباشرة.",
      mzBadge: "🇲🇿 خطوط الإمداد الأفريقية",
      mzTitle: "دعم مشاريع البنية التحتية الاستراتيجية في موزمبيق",
      mzDesc: "مع تشهد موزمبيق تطورًا هائلاً في قطاعات التعدين، ولوجستيات الغاز، وممرات النقل، توفر مجموعة سيال الأساس المادي لهذه المشاريع. نحن نستورد ونوزع المعدات الصناعية بالجملة، والفولاذ الإنشائي، والمثبتات عالية المقاومة، ومعدات السلامة. ومن خلال وكلائنا الإقليميين للتخليص في مابوتو وبيرا، ندير عملية الاستيراد بأكملها من تفريغ الحاويات إلى التخزين في موقع المشروع.",
      cat1Title: "المواد الإنشائية",
      cat1Desc: "حديد التسليح، والجسور الحديدية، والشبك السلكي، وحلول القوالب الخشبية والمعدنية.",
      cat2Title: "المثبتات والتجهيز",
      cat2Desc: "البراغي عالية المقاومة، والمثبتات، والخطافات، والحبال السلكية، وأدوات الرفع والتثبيت.",
      cat3Title: "سلامة الموقع والأنابيب",
      cat3Desc: "الأنابيب الفولاذية، والصمامات، ومعدات السلامة المتخصصة، والأدوات الصناعية.",
      integrityTitle: "حالة سلامة التوريد",
      routeTitle: "مسار الشحن:",
      routeVal: "نينغبو ➔ ميناء مابوتو",
      clearTitle: "وقت التخليص:",
      clearVal: "أقل من 7 أيام",
      qualityTitle: "ضمان الجودة:",
      qualityVal: "معتمد 100٪",
      reachTitle: "نطاق التوزيع:",
      reachVal: "مابوتو، بيرا، ناكالا",
      procBadge: "تكامل المشتريات",
      procHeading: "التكامل السلس مع مركز مشتريات إيو",
      procTitle: "مركز مشتريات الصين",
      proc1Title: "روابط مصانع مباشرة",
      proc1Desc: "شراكة مباشرة مع مصانع الصلب الرائدة ومصانع الأدوات في مقاطعتي جيجيانغ وجيانغسو.",
      proc2Title: "ميزة السعر بالجملة",
      proc2Desc: "شراء كميات كبيرة مباشرة من المصادر يلغي عمولات الوسطاء المتعددة.",
      proc3Title: "التصنيع المخصص",
      proc3Desc: "ضمان إمكانية قطع الفولاذ الإنشائي وتثقيبه مسبقًا وتصنيعه وفقًا للمخططات المخصصة.",
      procDesc: "ينسق مركز مشتريات مجموعة سيال في الصين عملية التصنيع والتحميل والتفتيش بأكملها. نجري عمليات تدقيق سماكة الصلب، واختبارات التحميل، وفحوصات الطلاء على جميع مواد البناء قبل إغلاق الحاويات. تحمي هذه القناة المباشرة المشاريع الأفريقية من المواد رديئة الجودة وتكاليف الوسطاء المرتفعة.",
      cta: "تقديم طلب عرض أسعار للمواد بالجملة",
    },
    contact: {
      badge: "مكتب الاستعلامات",
      heading: "توجيه الاتصالات المؤسسية B2B",
      desc: "تواصل مباشرة مع أقسامنا المتعددة الولايات. اختر سوقك المستهدف أو قسمك لتوجيه طلب عرض الأسعار مباشرة إلى المكتب الإقليمي المناسب.",
      formTitle: "بوابة توجيه استفسارات B2B",
      formDesc: "اختر القسم ومركز العمليات لضمان التوجيه الفوري لمدير القسم المعني.",
      companyName: "اسم المؤسسة / الشركة",
      contactName: "اسم جهة الاتصال الرئيسية",
      email: "البريد الإلكتروني للشركة",
      phone: "رقم الهاتف المباشر (مع رمز الدولة)",
      division: "القسم المستهدف",
      selectDiv: "اختر القسم المستهدف",
      destHub: "مركز العمليات المقصود",
      selectHub: "اختر مركز العمليات",
      details: "تفاصيل نطاق الاستفسار ومواصفات طلب عرض الأسعار (RFQ)",
      placeholderDetails: "يرجى تقديم الأبعاد، والحجم، ووجهة الشحن، والجدول الزمني المتوقع للتسليم...",
      submitting: "توجيه طلب عرض الأسعار...",
      submit: "إرسال استفسار B2B",
      successTitle: "تم توجيه الاستفسار بنجاح",
      successDesc: "تم تسجيل طلب عرض الأسعار وتوجيهه إلى المكتب الإقليمي المعني. سيتواصل معك مدير القسم عبر البريد الإلكتروني قريبًا.",
      errTitle: "خطأ في الإرسال",
      errDesc: "لم نتمكن من توجيه الاستفسار. يرجى التحقق من الاتصال بالشبكة والمحاولة مرة أخرى.",
      infoTitle: "الإحداثيات المؤسسية",
      hqTitle: "المقر العالمي",
      hqVal: "مسقط، سلطنة عمان",
      emailTitle: "البريد الإلكتروني المركزي للمؤسسة",
      wechatTitle: "معرف WeChat للمؤسسة",
      workTitle: "ساعات العمل الرسمية",
      workVal: "08:00 - 17:00 (GMT+4) | الاثنين - الجمعة",
    }
  },
  zh: {
    navbar: {
      home: "首页",
      about: "关于我们",
      machinery: "重型机械",
      parts: "汽车配件",
      hardware: "工业五金",
      contact: "联系我们",
      getInTouch: "取得联系",
      announcement: "SIAL 全球 | 全球工业采购生态系统 — 工厂直营重型机械、YSIT® 汽车配件和 SADAAN® 五金工具。",
    },
    footer: {
      divisions: "业务部门",
      platforms: "旗下平台",
      operations: "全球运营",
      contacts: "企业联系方式",
      centralEmail: "总部邮箱",
      wechat: "企业微信 ID",
      governance: "确保多司法管辖区合规治理。",
      ceoMessage: "总裁致辞",
      b2bInquiry: "B2B 询盘分发",
    },
    home: {
      legacyBadge: "🛡️ 18年全球合规治理传承",
      heroTitle: "多司法管辖区工业贸易与",
      heroHighlight: "基础设施采购",
      heroDesc: "作为一家精英跨国企业，SIAL 集团在全球工业贸易通道中引领卓越。我们的业务涵盖重型建筑机械销售与起重机租赁、批发原装汽车零部件出口以及全方位工地五金建材采购。通过将东亚的工厂生产线直接与海湾合作委员会（GCC）和非洲的高需求市场连接，我们确保了一流的质量控制、供应链韧性与全球物流效率。",
      routeInquiry: "提交 B2B 询盘",
      ceoBio: "集团履历",
      explore: "探索",
      edgeTitle: "我们的竞争优势：",
      edgeHighlight: "工厂直供与零中间商差价",
      edgeDesc: "与通过层层加价抬高成本的传统贸易商不同，SIAL 集团在全球关键经济枢纽运营自有的工厂直供采购中心。通过控制我们自己的国际采购网络，我们为全球企业确保了出厂价格、绝对的供应链透明度以及优质的质量保证。",
      koreaTitle: "战略汽车配件采购总部",
      koreaEntity: "运营实体：SIAL & Young A Trading Co.",
      koreaDesc: "与韩国顶尖汽车及重型机械零部件制造商深度整合，运营 B2B 业务。我们专注于将韩国生产线的批发原装汽车零配件（现代、起亚及商用车队配件）直接大批量出口到全球市场，省去中间商费用。",
      chinaTitle: "首要工业五金采购枢纽",
      chinaEntity: "运营实体：义乌市西阿尔国际贸易有限公司",
      chinaDesc: "管理庞大的工业采购与基础设施物流网络。该枢纽推动全品类工业五金、重型电动工具及大宗工地设备的直接采购，并针对销往非洲和海湾地区的集装箱直邮及分销网络进行优化。",
      whyChooseTitle: "为什么全球合作伙伴选择 SIAL 集团",
      whyChoose1Title: "出厂价格直供",
      whyChoose1Desc: "100% 消除第三方贸易代理利润和隐藏的中介费用。",
      whyChoose2Title: "严苛的质量保障",
      whyChoose2Desc: "直接在制造商层面进行端到端的质量控制和出货前检验。",
      whyChoose3Title: "无与伦比的供应链韧性",
      whyChoose3Desc: "在完善的企业合规框架下运营，确保多司法管辖区物流通畅与安全配送。",
      whyChoose4Title: "18+年 B2B 贸易专业经验",
      whyChoose4Desc: "数十年的跨境贸易谈判、国际采购积淀以及跨国供应链管理经验。",
      ceoMessageTitle: "集团总裁致辞",
      ceoSubtitle: "穆罕默德·阿姆贾德：供应链韧性的缔造者",
      ceoDesc1: "在穆罕默德·阿姆贾德的领导下，SIAL 集团历经近二十年的发展，从地方贸易代理成长为多司法管辖区的工业巨头。通过建立从韩国、中国到海湾地区和非洲的直供通道与航线，他为供应链独立性树立了行业新标杆。",
      ceoDesc2: "他的战略重心结合了对区域合规协议的严格遵守（例如沙特阿拉伯的 SASO、阿曼的 OPAL 以及莫桑比克马普托港口的清关运营）与 B2B 物流谈判，为我们的企业客户确保了直接的成本优势。",
      ceoConsultation: "预约 B2B 咨询",
      divisionsTitle: "我们的业务板块",
      divisionsSubtitle: "探索我们整合的业务板块，推动 GCC、非洲及东亚地区的增长与韧性。",
      machineryTitle: "重型机械部门",
      machineryDesc: "阿曼（SK Transports）、沙特阿拉伯（SIAL 国际公司）及巴基斯坦进口的重型起重机设备销售、租赁与配件分销。",
      partsTitle: "汽车配件分销",
      partsDesc: "为现代和起亚车型提供大批量优质原厂与替代零配件，直接由韩国及中国义乌网络采购供应。",
      hardwareTitle: "工业五金建材",
      hardwareDesc: "面向莫桑比克的基础设施建材分销，提供由我们中国采购中心直接出厂的优质建筑材料。",
      stats1: "年行业传承",
      stats2: "全球运营中心",
      stats3: "中间商利润",
      stats4: "严格质检",
    },
    about: {
      whoWeAre: "我们是谁",
      title: "18年多司法管辖区合规治理",
      desc: "近二十年来，SIAL 集团一直是多司法管辖区治理与跨境供应链优化的先驱。我们的运营总部战略性地分布于韩国、中国、阿曼、沙特阿拉伯和东非，将全球主要工业中心与新兴市场连接起来。在集团总裁穆罕默德·阿姆贾德对贸易合规、高层外交谈判和工厂直供采购的严格承诺指导下，集团在重型起重机械销售与租赁、原装起亚与现代汽车配件以及大宗工业五金建材领域确保了无与伦比的供应链韧性。我们透明的企业治理框架确保了无缝的国际合规性，与全球区域分销商、国有企业和私人商业车队建立了深厚互信的合作伙伴关系。",
      ceoProfileTitle: "高管领导力档案",
      ceoProfileHeading: "穆罕默德·阿姆贾德：供应链远见传承者",
      ceoQuote: "韧性不仅是供应链封锁中的幸存，更是建立专属渠道以确保我们的合作伙伴永远不会掉链子。",
      ceoDelegate: "🏛️ GCC 与东亚贸易代表",
      ceoDesc1: "集团总裁兼创始人穆罕默德·阿姆贾德创立 SIAL 集团的初衷是建立直接、互信的跨境合作关系。他很早就意识到中间商差价会削弱供应链效率，因此花了近二十年时间打造工厂直采网络。",
      ceoDesc2: "他的国际贸易谈判专长得到了健全的法律与合规框架支持。他的业务跨越多个司法管辖区，使 SIAL 集团能够无缝应对韩国、中国、海湾地区（阿曼和沙特）以及非洲（莫桑比克）的贸易合规、进口关税和海关协议。",
      ceoDesc3: "为了支持这些运营并优化面对客户的交付，SIAL 集团搭建了专门的线上平台，包括用于重型机械车队运营的 SK Transports Oman，以及用于汽车配件采购和机械服务的 Sial Kingdom 和 Yahya Auto Parts。",
      focusAreas: "核心关注领域",
      focusValue: "跨境关税与合规治理",
      strategicHubs: "战略运营中心",
      strategicValue: "首尔、义乌、马斯喀特、吉达",
      pillarsTitle: "企业核心基石",
      pillarsHeading: "集团核心实力",
      pillar1Title: "全球供应链韧性",
      pillar1Desc: "通过保持对中国和韩国采购中心的所有权，SIAL 集团确保了现货库存，保护客户免受突发海运滞港和地缘政治供应冲击的影响。",
      pillar2Title: "贸易谈判与资源整合",
      pillar2Desc: "我们总裁与国际港口管理局及船运公司的直接合作关系使得货物能够获得加急通关与极其优惠的运费协议。",
      pillar3Title: "多司法管辖区合规治理",
      pillar3Desc: "严格遵守区域企业合规法律，包括沙特阿拉伯的 SASO、阿曼的 OPAL 以及莫桑比克和南亚的海关清关协议。",
      networkTitle: "企业全球版图",
      networkHeading: "我们全球的企业网络",
      networkDesc: "SIAL 集团跨越多个国际司法管辖区运营。筛选我们旗下的 10 家注册子公司、物流管道和直接采购中心。",
    },
    machinery: {
      titleBadge: "部门画像",
      heading: "重型机械与车队物流",
      subtitle: "提供重型移动式起重机、工程车辆及重型备件。在严格的质量保证下，我们的部门在三个关键的区域中心开展运营。",
      omanBadge: "🇴🇲 阿曼业务中心",
      omanTitle: "移动起重机销售与租赁的 GCC 领跑者",
      omanDesc: "十多年来，SK Transports Oman 一直是阿曼苏丹国重型起重解决方案的黄金标准。我们专注于高容量车载起重机、移动式伸缩吊车和履带吊，服务于大型油气管道、海运货物项目和城市基础设施建设。",
      omanFeature1: "✓ 25至500吨起重能力",
      omanFeature2: "✓ OPAL 认证的操作员团队",
      omanFeature3: "✓ 24/7 工地现场技术支持",
      omanCta: "访问 SK Transports Oman 官网 ↗",
      fleetTitle: "在役起重机车队集锦",
      fleetBadge: "PDO 安全认证车队",
      saBadge: "🇸🇦 沙特阿拉伯拓展区",
      saTitle: "新成立的租赁车队与重型配件中心",
      saDesc: "将 SIAL 的业务版图拓展至吉达和东部省，以支持庞大的沙特“2030愿景”基建项目。 SIAL 国际公司提供越野移动起重机销售、长期车队租赁以及高品质重型备件分销。",
      saFeature1: "由韩国采购网络直接替换原厂配件",
      saFeature2: "移动式起重机保养、维修与吊装服务",
      saFeature3: "完全符合 SASO 和沙特油田安全管理标准",
      saCta: "索取沙特项目报价",
      pkBadge: "🇵🇰 巴基斯坦业务中心",
      pkTitle: "东亚采购节点与区域进口商",
      pkDesc: "大型进口和区域分销高品质工程机械与特种农业装备。直接从我们的东亚采购网络直供，消除第三方差价，向巴基斯坦承包商和农业合作社直接供应重型机械。",
      pkFeature1: "履带式拖拉机及收割装载机",
      pkFeature2: "特种农业播种与耕作机械",
      pkFeature3: "直接从韩国和义乌采购中心集装箱进口",
      pkCta: "咨询巴基斯坦进口业务",
    },
    parts: {
      badge: "汽车配件部门",
      heading: "原装正品零配件分销",
      subtitle: "大批量分销渠道，为韩国乘用车和商用车提供全新及二手原装零配件。与 OEM 制造商和经过验证的出口商直接整合。",
      specBadge: "核心专业领域",
      specHeading: "现代与起亚零配件无缝供应",
      specDesc: "我们专注于为现代和起亚所有主流车型提供全新和二手原装零配件。我们的大宗分销渠道服务于 GCC 仓储分销商、大型商用车队和国家级零售连锁。通过绕过多个代理商渠道，我们直接从原产地锁定高周转零配件。",
      cat1Title: "发动机与传动系统",
      cat1Desc: "完整发动机、变速箱、活塞及传动桥配件。",
      cat2Title: "悬挂与转向系统",
      cat2Desc: "减震器、连杆、控制臂和转向机总成。",
      cat3Title: "电气与车身覆盖件",
      cat3Desc: "发电机、电脑板 (ECU)、大灯、保险杠和车身饰条。",
      cat4Title: "高磨损消耗品",
      cat4Desc: "刹车盘片、过滤系统、火花塞和密封垫圈。",
      infraHeading: "海湾地区分销基础设施",
      infraOmanTitle: "阿曼枢纽 (Sial Kingdom Trading LLC)",
      infraOmanDesc: "Sial Kingdom Trading LLC 是我们在马斯喀特塞卜的主要服务平台，负责协调本地车队运营以及在阿曼苏丹国全境分销纯正汽车配件。",
      infraSaTitle: "沙特阿拉伯拓展区",
      infraSaDesc: "复制阿曼的成功运作模式，我们位于吉达的业务部门现在向整个沙特主要经济走廊的零售商和企业运输车队分销大批量配件。",
      hubsBadge: "旗下服务平台",
      hubsHeading: "我们的汽配销售与售后维修中心",
      hubsDesc: "SIAL 集团在阿曼苏丹国运营两个著名的面对客户的汽配品牌，提供厂价直供配件与专业机械维修服务。",
      skBadge: "阿曼马斯喀特部门",
      skTitle: "Sial Kingdom Trading LLC",
      skDesc: "Sial Kingdom 是位于阿曼马斯喀特马贝拉工业区的一家备受信任的汽车维修厂和正品零件经销商。他们专注于起亚和现代车辆，使用厂价直供的替换零件提供从日常诊断到高级机械与车身修理的全方位服务。",
      skCta: "探索 Sial Kingdom 网站 ↗",
      yahyaBadge: "全球物流枢纽",
      yahyaTitle: "雅雅汽车配件 (Yahya Auto Parts)",
      yahyaDesc: "雅雅汽车配件（Yahya Bin Khalfan LLC）成立于2006年，已发展成为阿曼领先的现代、起亚和捷尼赛思原装零件批发与零售分销商，其采购和集运业务遍及韩国、中国和巴基斯坦。",
      yahyaCta: "探索雅雅汽车配件网站 ↗",
      integrityHeading: "直采源头保障",
      integrityDesc: "通过我们的专属采购中心，确保从工厂到车队的原装品质。",
      sourcingKorea: "我们设立在韩国首尔的首要东亚采购中心。我们直接与制造工厂和授权 OEM 渠道协调以获取全新零件，同时在集装箱装运前直接在现场检验和认证二手配件。",
      sourcingChina: "位于全球小商品贸易之都中国义乌。该枢纽对工业级零配件进行严格的质量审计并监督出口物流，确保每一批货物都符合国际质量标准。",
      erpTitle: "实时 ERP 系统跟踪",
      erpDesc: "利用我们定制的 Odoo ERP 仪表板实时监控海湾及非洲走廊的仓库物流、工厂直发订单、海上在途路径和区域合规审计。",
    },
    hardware: {
      badge: "工业五金部门",
      heading: "工业五金与工地建材",
      subtitle: "促进高强度结构材料的进口、清关和分销。将东非的大型基础设施建设与直接生产厂家紧密相连。",
      mzBadge: "🇲🇿 非洲供应通道",
      mzTitle: "助力莫桑比克战略性基建项目",
      mzDesc: "随着莫桑比克在矿业、天然气物流和交通走廊方面的蓬勃发展，SIAL 集团提供了坚实的物资保障。我们进口并分销大宗工业五金、结构钢材、高强度紧固件和工地防护用品。通过我们在马普托和贝拉的区域清关代理，我们管理从集装箱卸货到现场存储的整个进口流程。",
      cat1Title: "结构建材",
      cat1Desc: "螺纹钢、型钢梁、钢丝网以及脚手架模板解决方案。",
      cat2Title: "紧固件与索具吊装",
      cat2Desc: "高强度螺栓、锚栓、卸扣、钢丝绳以及起重滑轮组。",
      cat3Title: "工地安全与管网",
      cat3Desc: "钢管、阀门、特种防护装备以及工业级手动电动工具。",
      integrityTitle: "供应保障状态",
      routeTitle: "海运路线：",
      routeVal: "宁波港 ➔ 马普托港",
      clearTitle: "海关清关时间：",
      clearVal: "7天以内",
      qualityTitle: "质量保障：",
      qualityVal: "100% 官方认证",
      reachTitle: "分销覆盖：",
      reachVal: "马普托、贝拉、纳卡拉",
      procBadge: "采购端整合",
      procHeading: "与中国义乌采购枢纽无缝对接",
      procTitle: "中国采购中心",
      proc1Title: "直连制造工厂",
      proc1Desc: "与浙江、江苏等地的核心钢厂及五金工具制造厂建立直接合作关系。",
      proc2Title: "大宗采购价格优势",
      proc2Desc: "直接从源头采购大宗货物，消除了多层贸易商的佣金抽成与加价。",
      proc3Title: "定制切配加工",
      proc3Desc: "确保结构钢材可根据客户的工程蓝图在出厂前进行预切、预钻和加工。",
      procDesc: "SIAL 集团在中国的采购中心协调制造、装箱和质检的完整管道。在锁箱封条之前，我们对所有建材进行现场厚度抽检、拉力荷载测试和防锈涂层检验。这条直达通道保护了非洲基建项目免受劣质材料的影响，并省去了高昂的中间商费用。",
      cta: "提交大宗建材询盘 (RFQ)",
    },
    contact: {
      badge: "询盘中心",
      heading: "B2B 通讯分发路由",
      desc: "直接与我们的多司法管辖区业务部门联系。选择您的目标市场或业务部门，将您的询盘（RFQ）直接发送给相应的区域负责人。",
      formTitle: "B2B 询盘智能分发系统",
      formDesc: "选择业务板块及目标运营中心，确保询盘能被相关负责人第一时间接收处理。",
      companyName: "企业官方名称",
      contactName: "首要联系人姓名",
      email: "企业电子邮箱",
      phone: "直接联系电话 (包含国家代码)",
      division: "意向业务部门",
      selectDiv: "请选择意向业务部门",
      destHub: "目标运营中心",
      selectHub: "请选择目标运营中心",
      details: "详细的询价范围与规格说明",
      placeholderDetails: "请提供尺寸、采购数量、送货港口以及预期的交付时间表...",
      submitting: "正在分发询盘...",
      submit: "提交 B2B 询盘",
      successTitle: "询盘成功分发",
      successDesc: "您的询盘已被记录并分发至相应的区域办公室。部门负责人将很快通过电子邮件与您联系。",
      errTitle: "提交失败",
      errDesc: "无法提交询盘。请检查您的网络连接并重试。",
      infoTitle: "企业总部信息",
      hqTitle: "全球总部",
      hqVal: "阿曼苏丹国，马斯喀特",
      emailTitle: "中央企业邮箱",
      wechatTitle: "企业微信 ID",
      workTitle: "官方运营时间",
      workVal: "08:00 - 17:00 (GMT+4) | 周一至周五",
    }
  },
  ko: {
    navbar: {
      home: "홈",
      about: "회사 소개",
      machinery: "중장비",
      parts: "자동차 부품",
      hardware: "산업용 하드웨어",
      contact: "문의하기",
      getInTouch: "문의하기",
      announcement: "SIAL 글로벌 | 글로벌 산업 소싱 에코시스템 — 공장 직송 중장비, YSIT® 자동차 부품 및 SADAAN® 산업 하드웨어.",
    },
    footer: {
      divisions: "사업 부문",
      platforms: "운영 플랫폼",
      operations: "글로벌 네트워크",
      contacts: "기업 연락처",
      centralEmail: "대표 이메일",
      wechat: "WeChat 기업 ID",
      governance: "다국적 기업 지배구조 및 규정 준수 보장.",
      ceoMessage: "대표이사 인사말",
      b2bInquiry: "B2B 문의 라우팅",
    },
    home: {
      legacyBadge: "🛡️ 18년 글로벌 거버넌스 레거시",
      heroTitle: "다국적 산업 무역 및",
      heroHighlight: "인프라 자재 조달",
      heroDesc: "글로벌 비즈니스를 선도하는 초일류 다국적 기업 SIAL 그룹은 세계 무역의 기준을 제시합니다. SANY 등 최고급 건설 중장비 판매 및 크레인 임대 사업부터 현대·기아 자동차 정품 부품 도매 수출, 건설 현장용 하드웨어 및 인프라 자재의 원스톱 조달을 책임집니다. 동아시아 핵심 제조 라인과 GCC, 아프리카의 수요처를 다이렉트로 연결하여 업계 최고의 품질 관리, 탄탄한 공급망 밸류체인 및 효율적인 글로벌 통합 물류를 보장합니다.",
      routeInquiry: "B2B 문의하기",
      ceoBio: "그룹 이력",
      explore: "자세히 보기",
      edgeTitle: "당사만의 독보적인 차별점: ",
      edgeHighlight: "공장 직거래를 통한 유통 마진 제로화",
      edgeDesc: "불필요한 중개 업체를 거쳐 단가를 높이는 기존 무역 에이전트들과 다릅니다. SIAL 그룹은 글로벌 물류 허브에 자체 공장 직거래 소싱 네트워크를 구축하여 중간 마진을 완벽하게 없앴습니다. 직영 구매 라인을 직접 통제함으로써 글로벌 기업 파트너분들께 합리적인 공장 다이렉트 단가, 완벽하게 투명한 공급망 구조 및 철저한 품질 인증을 약속합니다.",
      koreaTitle: "자동차 부품 글로벌 조달 거점",
      koreaEntity: "운영 지사: SIAL & Young A Trading Co.",
      koreaDesc: "한국의 최고급 자동차 및 중장비 부품 제조사들과 다이렉트 협력 체계를 구축하여 운영하고 있습니다. 중간 유통 거품 없이 현대, 기아 정품 부품 및 상용 차량용 부품을 한국 공장 생산 라인에서 해외 주요 도매 시장으로 다이렉트 직수출합니다.",
      chinaTitle: "산업용 하드웨어 핵심 거점",
      chinaEntity: "운영 지사: Yiwu SIAL International Trading Co. Ltd.",
      chinaDesc: "세계 소상품 교역의 중심지인 중국 이우에서 대규모 산업용 하드웨어 및 건설 자재 소싱 네트워크를 총괄합니다. 건설 공구, 고장력 고정 장치 및 인프라 자재의 대량 매입에 특화되어 있으며 아프리카와 GCC 지역으로의 최적화된 물류 컨테이너 선적을 책임집니다.",
      whyChooseTitle: "글로벌 파트너들이 SIAL 그룹을 선택하는 이유",
      whyChoose1Title: "공장 다이렉트 단가 보장",
      whyChoose1Desc: "중간 중개 브로커 마진과 불투명한 유통 수수료를 100% 원천 제거했습니다.",
      whyChoose2Title: "철저한 전수 품질 검증",
      whyChoose2Desc: "제조 공장 생산 단계부터 출하 전 최종 검수까지 엄격한 자체 품질 테스트를 거칩니다.",
      whyChoose3Title: "안정적인 하이브리드 공급망",
      whyChoose3Desc: "글로벌 통관 리스크를 사전 방지하며 안정적인 하이브리드 육해상 물류 라인을 구축했습니다.",
      whyChoose4Title: "18년 이상의 기업 간(B2B) 무역 전문성",
      whyChoose4Desc: "수십 년간 축적된 글로벌 무역 협상력, 해외 조달 프로세스 노하우 및 다국적 공급망 관리 역량.",
      ceoMessageTitle: "그룹 CEO 메시지",
      ceoSubtitle: "무하마드 암자드: 탄탄하고 투명한 공급망 구축의 선두주자",
      ceoDesc1: "그룹 설립자 무하마드 암자드(Muhammad Amjad) 대표이사의 리더십 하에 SIAL 그룹은 소규모 무역상에서 다국적 지배구조를 갖춘 초대형 글로벌 산업 강자로 거듭났습니다. 한국, 중국의 핵심 제조 라인에서 GCC, 아프리카 시장까지 직영 해운 노선을 확보하여 타사 대비 강력한 독립 공급망을 완성했습니다.",
      ceoDesc2: "사우디아라비아의 SASO 인증, 오만의 OPAL 규정 준수, 모잠비크 마푸토 항만 통관 등 국가별 복잡한 무역 규제에 대한 완벽한 대처와 글로벌 물류 다이렉트 직거래를 통해 기업 파트너분들의 수입 마진을 극대화합니다.",
      ceoConsultation: "B2B 전문 상담 신청",
      divisionsTitle: "그룹 핵심 사업 분야",
      divisionsSubtitle: "GCC, 아프리카, 동아시아 시장에서 성장을 견인하고 있는 SIAL 그룹의 핵심 비즈니스 포트폴리오입니다.",
      machineryTitle: "건설 중장비 부문",
      machineryDesc: "오만(SK Transports), 사우디아라비아(SIAL International), 파키스탄 수입 부문을 아우르는 초대형 이동식 크레인 판매, 임대 및 특수 부품 조달 사업.",
      partsTitle: "자동차 부품 유통 부문",
      partsDesc: "현대, 기아 자동차의 고회전 순정 부품 및 대체 부품을 한국 및 중국 이우 허브에서 다이렉트로 대량 소싱 및 전 세계 유통.",
      hardwareTitle: "산업 하드웨어 부문",
      hardwareDesc: "모잠비크 국책 인프라 건설 현장에 필요한 철강 자재, 고강도 자재 및 각종 하드웨어를 중국 직영 허브에서 다이렉트로 공급.",
      stats1: "년 업력 레거시",
      stats2: "개 글로벌 허브",
      stats3: "중개 유통 마진",
      stats4: "품질 인증 완료",
    },
    about: {
      whoWeAre: "회사 정보",
      title: "18년 업력의 글로벌 거버넌스 기업",
      desc: "지난 18여 년간 SIAL 그룹은 다국적 거버넌스 확립과 다국간 공급망 최적화의 선도적 개척자 역할을 수행해 왔습니다. 한국, 중국, 오만, 사우디아라비아, 동아프리카 등지의 핵심 요충지에 직영 법인을 두고 동아시아의 제조 밸리체인과 신흥 개발 도상국 시장을 신속하게 이어왔습니다. 무하마드 암자드 대표이사의 무역 규정 준수 철학, 풍부한 크로스보더 협상 노하우, 공장 직거래 원칙을 근간으로 하여 건설 중장비 임대, 현대·기아 자동차 순정 부품 도매, 인프라용 산업 하드웨어 공급 부문에서 강력한 공급망 안정성을 선사합니다. 투명한 글로벌 지배구조 하에 지역 유통사, 공기업 및 대형 운송사들과 장기적인 신뢰 파트너십을 다지고 있습니다.",
      ceoProfileTitle: "경영진 소개",
      ceoProfileHeading: "무하마드 암자드: 글로벌 공급망 혁신가",
      ceoQuote: "진정한 공급망의 힘은 단순히 물류 대란에서 살아남는 것이 아니라, 파트너사가 결코 멈추지 않도록 직영 파이프라인을 완전히 지배하는 데서 나옵니다.",
      ceoDelegate: "🏛️ GCC & 동아시아 비즈니스 대표단",
      ceoDesc1: "그룹 설립자 무하마드 암자드 대표이사는 유통 거품을 걷어내고 해외 공장과 직거래하는 고신뢰 비즈니스 플랫폼을 지향하며 회사를 세웠습니다. 중간 유통상이 단가를 올리고 신속성을 해친다는 점을 기민하게 간파하여 생산 공장과의 직거래 파이프라인을 뚫는 데 오랜 열정을 쏟았습니다.",
      ceoDesc2: "그의 강력한 글로벌 무역 지식은 정교한 다국적 규정 준수 시스템을 통해 발현됩니다. 한국, 중국, GCC(오만, 사우디), 아프리카(모잠비크)를 넘나들며 복잡한 수입 관세, 통관 서류 심사, 국가 표준 인증 절차를 실수 없이 완료해 냅니다.",
      ceoDesc3: "또한 개별 사업 부문의 전문적 지원을 위해 중장비 직영 아웃소싱 플랫폼인 SK Transports Oman과 자동차 부품 전문 유통 및 정비 서비스를 운영하는 Sial Kingdom 및 Yahya Auto Parts를 성공적으로 구축하여 상생의 동반 성장을 이루고 있습니다.",
      focusAreas: "핵심 전문 역량",
      focusValue: "국가별 관세 및 수출입 규정 준수 (SASO, OPAL)",
      strategicHubs: "직영 조달 본부",
      strategicValue: "서울, 이우, Muscat, 제다",
      pillarsTitle: "기업 핵심 경쟁력",
      pillarsHeading: "당사 비즈니스 핵심 역량",
      pillar1Title: "공급망 리스크 사전 대응",
      pillar1Desc: "한국과 중국에 현지 조달 법인을 직접 소유하여 원자재 수급 불안정, 해운 대란 및 지정학적 리스크 속에서도 안정적으로 안전 재고를 확보해 드립니다.",
      pillar2Title: "물류 단가 협상 우위",
      pillar2Desc: "글로벌 대형 해운선사 및 항만 운영사들과 맺어온 파트너십을 바탕으로 신속 통관을 지원하며 최저 수준의 컨테이너 해상 운임을 보장합니다.",
      pillar3Title: "다국가 규제 인증 신속 해결",
      pillar3Desc: "사우디아라비아 SASO, 오만 PDO/OPAL 인증을 포함하여 모잠비크 통관 규정 등 지역별 기업 라이선스 및 인증을 원스톱으로 신속 처리합니다.",
      networkTitle: "글로벌 네트워크",
      networkHeading: "SIAL 그룹 글로벌 법인 주소록",
      networkDesc: "SIAL 그룹은 다수의 해외 법인을 직영 체제로 관리합니다. 국가별 10대 핵심 현지 법인, 물류 파이프라인 및 조달 본부 정보를 확인해 보세요.",
    },
    machinery: {
      titleBadge: "부문 소개",
      heading: "중장비 판매 및 임대 물류",
      subtitle: "고용량 이동식 크레인, 건설 장비 및 중장비용 특수 부품 조달을 전문으로 합니다. 엄격한 안전 기준 하에 3대 글로벌 거점에서 직영 운영되고 있습니다.",
      omanBadge: "🇴🇲 오만 지사",
      omanTitle: "오만 1위 대형 크레인 임대 & 엔지니어링 리더",
      omanDesc: "지난 10년 이상 오만 전역의 국책 오일·가스 플랜트 현장, 항만 하역 및 도시 인프라 건설 현장에서 독보적인 크레인 임대 솔루션을 제공해 온 SK Transports Oman입니다. 고용량 트럭 크레인, 전지형(All-Terrain) 크레인 및 궤도형(Crawler) 크레인을 직접 소유하여 운영합니다.",
      omanFeature1: "✓ 25톤부터 500톤까지 풀 라인업 보유",
      omanFeature2: "✓ 오만 최고 등급 OPAL 전문 자격 인증 조종사 배치",
      omanFeature3: "✓ 24시간 연중무휴 현장 긴급 점검 및 유지보수 지원",
      omanCta: "SK Transports Oman 공식 사이트 방문 ↗",
      fleetTitle: "주요 가동 크레인 라인업 쇼케이스",
      fleetBadge: "PDO 최고 안전 등급 획득",
      saBadge: "🇸🇦 사우디아라비아 지사",
      saTitle: "네옴시티 등 비전 2030 국책 프로젝트 중장비 공급",
      saDesc: "사우디아라비아 제다 및 동부 주 유수 산업 단지에 법인을 설립하고 비전 2030 국책 사업에 중장비 크레인 임대 및 순정 부품 유통을 지원합니다. 장단기 크레인 대여와 함께 중장비 특수 엔진 부품을 적기에 납품합니다.",
      saFeature1: "한국 및 중국 허브에서 정비 부품 다이렉트 직수송",
      saFeature2: "현장 전지형 크레인 리깅 및 긴급 엔지니어링 지원",
      saFeature3: "사우디 SASO 안전 기준 및 국영 아람코(Aramco) 안전 규격 만족",
      saCta: "사우디아라비아 현장 견적 문의",
      pkBadge: "🇵🇰 파키스탄 지사",
      pkTitle: "동아시아 건설 장비 조달 및 파키스탄 총판 수입",
      pkDesc: "동아시아 조달 본부에서 선별한 고성능 굴삭기, 트랙터, 농업용 대형 파종기 등을 파키스탄 건설 인프라 및 대규모 농경 단지에 공급합니다. 수입 관세를 최적화하여 중간 유통상 없이 대량 수입 공급합니다.",
      pkFeature1: "궤도형 트랙터 및 대형 하베스트 로더 수입",
      pkFeature2: "대형 정밀 파종기 등 농업 기계 총판 공급",
      pkFeature3: "한국 및 이우 조달 법인을 통한 다이렉트 인보이스 발행 및 직수입",
      pkCta: "파키스탄 수입 중장비 견적 문의",
    },
    parts: {
      badge: "자동차 부품 부문",
      heading: "현대·기아 자동차 정품 부품 도매 유통",
      subtitle: "현대 및 기아 자동차의 고회전 순정 신품 및 중고 부품을 대량으로 유통합니다. 제조사 및 1차 벤더 수출 라인과 다이렉트로 통합되어 있습니다.",
      specBadge: "전문 유통 역량",
      specHeading: "현대 & 기아 자동차 핵심 전장/엔진 부품 독점 공급",
      specDesc: "현대 및 기아 자동차의 모든 차종에 해당하는 순정 신품 및 A급 중고 재생 부품 도매를 전문으로 합니다. 당사의 컨테이너 단위 유통 채널은 GCC 대형 도매 창고, 중동 대규모 프랜차이즈 정비사 및 대형 택시 운송 회사에 부품을 원스톱 공급합니다.",
      cat1Title: "엔진 및 변속기",
      cat1Desc: "엔진 어셈블리, 트랜스미션 기어박스, 피스톤 및 구동축 부품 일체.",
      cat2Title: "서스펜션 및 조향 장치",
      cat2Desc: "쇼크 업쇼버, 타이로드 엔드, 컨트롤 암 및 스티어링 랙.",
      cat3Title: "전장 부품 및 차체 아웃사이드",
      cat3Desc: "알터네이터, ECU 컴퓨터, 순정 헤드램프, 앞뒤 범퍼 및 도어 아웃사이드 패널.",
      cat4Title: "필수 고마모성 소모품",
      cat4Desc: "순정 브레이크 패드/디스크, 오일/에어 필터, 스파크 플러그 및 엔진 가스켓.",
      infraHeading: "GCC 지역 광역 유통망 인프라",
      infraOmanTitle: "오만 중동 허브 (Sial Kingdom Trading LLC)",
      infraOmanDesc: "무스카트 시브에 위치한 Sial Kingdom Trading LLC는 직영 정비 및 순정 부품 유통망을 통해 오만 전역의 상용차 네트워크와 딜러들에게 완벽한 물류 서비스를 제공합니다.",
      infraSaTitle: "사우디아라비아 광역망 유통",
      infraSaDesc: "오만 법인의 성공적인 시스템을 사우디아라비아 제다 물류창고에 이식하여, 사우디 전역의 자동차 순정 부품 도소매 유통망을 빠르게 장악해 가고 있습니다.",
      hubsBadge: "직영 서비스 플랫폼",
      hubsHeading: "오만 무스카트 랜드마크 정비 & 유통 브랜드",
      hubsDesc: "SIAL 그룹은 오만 무스카트 지역에서 소비자 접근성이 뛰어난 두 곳의 자동차 종합 서비스 플랫폼을 직영 운영하여 순정 부품 교체와 정밀 기계 수리를 제공합니다.",
      skBadge: "무스카트 시브 지사",
      skTitle: "Sial Kingdom Trading LLC",
      skDesc: "무스카트 최대 산업 단지인 마벨라(Mabila) 6구역에 위치한 프리미엄 자동차 정비 및 정품 부품 공급 센터입니다. 현대·기아 차량만을 정밀 타깃하여 고난도 하체 엔진 수리, 판금 도색 및 전용 스캐너 진단 서비스를 전개합니다.",
      skCta: "Sial Kingdom 공식 사이트 방문 ↗",
      yahyaBadge: "중동 부품 도소매 총판",
      yahyaTitle: "Yahya Auto Parts (야야 오토파츠)",
      yahyaDesc: "2006년 무스카트에서 첫 발을 뗀 이후 오만을 대표하는 현대, 기아, 제네시스 부품 전문 도소매 대리점으로 우뚝 섰습니다. 한국 서울 본사 및 중국 조달 부서와 긴밀히 연계되어 있습니다.",
      yahyaCta: "Yahya Auto Parts 공식 사이트 방문 ↗",
      integrityHeading: "원산지 직수입의 정직함",
      integrityDesc: "해외 직영 소싱 본부를 통해 공장부터 선적까지 거품 없는 투명한 유통 단가를 보장합니다.",
      sourcingKorea: "한국 서울에 상주하는 SIAL & Young A 조달 본부입니다. 모비스(Mobis) 순정 부품 1차 유통망과 다이렉트로 연계하여 부품을 확보하며, 폐차 재생용 A급 중고 엔진과 트랜스미션을 야드에서 직접 확인하고 컨테이너 선적 전수 검수를 완료합니다.",
      sourcingChina: "중국 절강성 이우(Yiwu)에 위치한 글로벌 도매 무역 허브입니다. 특수 배선, 대체 램프 등 검증된 대체 부품(OEM) 제조업체들을 엄선하여 품질 검사(QA)를 마친 후 컨테이너 운송을 진행합니다.",
      erpTitle: "실시간 Odoo ERP 모니터링",
      erpDesc: "커스터마이징된 Odoo ERP 시스템을 기반으로 원거리 법인 간의 재고 현황, 제조사 발주 시점, 해상 운송 배선 스케줄, 수입 통관 대기 현황을 원스톱으로 관리합니다.",
    },
    hardware: {
      badge: "산업용 자재 부문",
      heading: "산업 하드웨어 및 건설용 철강 부자재",
      subtitle: "고강도 구조용 철강재, 배관 설비 자재 및 안전 자재의 대량 수입과 현장 물류를 책임집니다. 동아프리카의 대형 인프라 건설 프로젝트에 공장 다이렉트 직배송을 지원합니다.",
      mzBadge: "🇲🇿 아프리카 인프라 파이프라인",
      mzTitle: "모잠비크 국책 광산 및 가스 전용 인프라 건설 자재 단독 공급",
      mzDesc: "광산 개발과 천연가스 배관망 건설이 활발한 모잠비크의 국책 인프라 프로젝트에 든든한 산업용 하드웨어를 공급합니다. 고강도 이형철근, H빔 철강재, 고장력 볼트류, 안전 장비 등을 대량 수입 및 유통합니다. 모잠비크 수도 마푸토 및 베이라 항만에 상주하는 당사 파트너 통관사를 통해 컨테이너 하역부터 건설 현장 보관 창고까지 일괄 하이웨이 물류를 진행합니다.",
      cat1Title: "구조용 철강재",
      cat1Desc: "고강도 이형철근, H빔, 형강, 와이어 매쉬 및 거푸집 등 형틀 자재 일체.",
      cat2Title: "고장력 패스너 & 로프",
      cat2Desc: "고장력 앵커 볼트, 샤클, 슬링 벨트, 크레인 와이어 로프 및 도르래 류.",
      cat3Title: "현대식 배관 설비 및 공구",
      cat3Desc: "산업용 강관 파이프, 대형 밸브, 현장 전용 개인 안전 장구 및 대형 특수 공구류.",
      integrityTitle: "공급망 안정성 지표",
      routeTitle: "해상 해운 노선:",
      routeVal: "중국 닝보항 ➔ 모잠비크 마푸토항",
      clearTitle: "통관 소요 시간:",
      clearVal: "영업일 기준 7일 이내",
      qualityTitle: "품질 인증 여부:",
      qualityVal: "국제 시험 성적서 보유 (100%)",
      reachTitle: "광역 물류 커버리지:",
      reachVal: "Maputo, Beira, Nacala 현장 직배송",
      procBadge: "조달 본부 시너지",
      procHeading: "중국 이우 조달 본부를 통한 대량 소싱 역량",
      procTitle: "중국 이우 직영 법인",
      proc1Title: "중국 철강 제조사 직거래",
      proc1Desc: "중국 최대 철강 생산 기지인 강소성 및 절강성 제철소들과 다이렉트 연동 단가 협상 진행.",
      proc2Title: "단가 후려치기 차단",
      proc2Desc: "중간 브로커의 대리 커미션과 가공 비용을 완벽히 차단하여 공장 출하가 수준으로 단가를 맞춥니다.",
      proc3Title: "사전 도면 정밀 가공",
      proc3Desc: "H빔 및 구조용 강재를 건설사 도면에 맞추어 공장에서 사전 컷팅 및 타공 가공하여 납품 가능.",
      procDesc: "중국 이우 SIAL 조달 본부에서는 철강 자재의 두께 오차 확인, 볼트의 인장 강도 테스트, 도금 도장 두께 검사를 직접 주관합니다. 컨테이너 실링 잠금장치를 닫기 전 철저한 사전 QA를 통해 아프리카 현장에 부적합한 자재가 유입되는 리스크를 원천 차단하고 물류비 낭비를 예방합니다.",
      cta: "건설 자재 대량 견적 요청 (RFQ)",
    },
    contact: {
      badge: "B2B 고객 지원",
      heading: "B2B 문의 실시간 채널",
      desc: "다국적 지사 및 사업 부문에 다이렉트로 연락해 보세요. 수입 희망 국가와 비즈니스 파트를 지정하시면 해당 국가 본사의 담당 임원에게 실시간 전달됩니다.",
      formTitle: "B2B 문의 접수 포털",
      formDesc: "문의하고자 하시는 세부 사업 부문과 수령 지사를 선택해 주시면 보다 빠른 답변을 받아보실 수 있습니다.",
      companyName: "회사명 (영문/국문)",
      contactName: "담당자 성함",
      email: "회사 업무용 이메일 주소",
      phone: "전화번호 (국가번호 포함)",
      division: "비즈니스 부문",
      selectDiv: "문의 부문을 선택하세요",
      destHub: "지정 수입 법인",
      selectHub: "수령 허브를 선택하세요",
      details: "상세 견적 사양 및 문의 내용",
      placeholderDetails: "규격, 예상 수입 컨테이너 수량, 최종 납품 희망 항구, 납품 희망 일정 등을 기재해 주시면 보다 신속한 견적서 작성이 가능합니다...",
      submitting: "문의 사항 전달 중...",
      submit: "견적 문의서 제출",
      successTitle: "문의 접수 완료",
      successDesc: "고객님의 문의서가 성공적으로 접수되어 해당 법인 담당 이사에게 즉시 전달되었습니다. 기재해 주신 이메일로 신속히 견적서 및 답변을 보내드리겠습니다.",
      errTitle: "접수 오류",
      errDesc: "일시적인 네트워크 장애로 인해 발송에 실패했습니다. 잠시 후 다시 시도해 주세요.",
      infoTitle: "SIAL 글로벌 본사 정보",
      hqTitle: "글로벌 헤드쿼터",
      hqVal: "Muscat, Sultanate of Oman (오만 무스카트)",
      emailTitle: "대표 이메일 주소",
      wechatTitle: "WeChat 기업 메신저 ID",
      workTitle: "본사 공식 업무 시간",
      workVal: "08:00 - 17:00 (GMT+4) | 월요일 - 금요일",
    }
  },
  ur: {
    navbar: {
      home: "ہوم",
      about: "ہمارے بارے میں",
      machinery: "ہیوی مشینری",
      parts: "اسپیئر پارٹس",
      hardware: "انڈسٹریل ہارڈویئر",
      contact: "رابطہ کریں",
      getInTouch: "رابطہ کریں",
      announcement: "سیال گلوبال | عالمی صنعتی سورسنگ ایکو سسٹم — فیکٹری سے براہ راست بھاری مشینری، ®YSIT آٹو پارٹس اور ®SADAAN ہارڈ ویئر سپلائیز۔",
    },
    footer: {
      divisions: "شعبہ جات",
      platforms: "ہمارے پلیٹ فارمز",
      operations: "عالمی نیٹ ورک",
      contacts: "کارپوریٹ رابطے",
      centralEmail: "مرکزی ای میل",
      wechat: "WeChat کارپوریٹ آئی ڈی",
      governance: "ملٹی جورسڈکشنل گورننس کی ضمانت۔",
      ceoMessage: "سی ای او کا پیغام",
      b2bInquiry: "B2B انکوائری روٹنگ",
    },
    home: {
      legacyBadge: "🛡️ 18 سالہ عالمی گورننس کی میراث",
      heroTitle: "ملٹی جورسڈکشنل انڈسٹریل ٹریڈنگ اور",
      heroHighlight: "انفراسٹرکچر کی خریداری",
      heroDesc: "ایک ممتاز کثیر القومی ادارے کے طور پر، سیال گروپ (SIAL Group) عالمی راہداریوں میں صنعتی تجارت کی عمدگی کو فروغ دیتا ہے۔ ہماری صلاحیتوں میں ہیوی کنسٹرکشن مشینری کی فروخت اور کرین کے کرایے کے ساتھ ساتھ تھوک قیمت پر گاڑیوں کے حقیقی اسپیئر پارٹس کی برآمد اور تعمیراتی سائٹس کے لیے انڈسٹریل ہارڈویئر کی خریداری شامل ہے۔ مشرقی ایشیا کی براہ راست پیداواری لائنوں کو جی سی سی (GCC) اور افریقہ کی اعلیٰ طلب والی منڈیوں سے جوڑ کر، ہم معیاری کنٹرول، سپلائی چین کی مضبوطی، اور عالمی لاجسٹکس کی کارکردگی کی ضمانت دیتے ہیں۔",
      routeInquiry: "B2B انکوائری روٹ کریں",
      ceoBio: "گروپ کی سوانح عمری",
      explore: "تفصیلات",
      edgeTitle: "ہماری مسابقتی برتری: ",
      edgeHighlight: "فیکٹری ڈائریکٹ سورسنگ اور زیرو بروکر مارجن",
      edgeDesc: "روایتی تجارتی بروکرز کے برعکس جو بیچ میں کمیشن لے کر قیمتیں بڑھاتے ہیں، سیال گروپ عالمی اقتصادی مراکز میں اپنے فیکٹری ڈائریکٹ سورسنگ نیٹ ورک چلاتا ہے۔ اپنے بین الاقوامی سورسنگ نیٹ ورکس کو خود کنٹرول کر کے، ہم عالمی اداروں کے لیے براہ راست فیکٹری قیمتوں، سپلائی چین کی مکمل شفافیت اور بہترین معیار کی ضمانت دیتے ہیں۔",
      koreaTitle: "گاڑیوں کے پارٹس کا اسٹریٹجک سورسنگ ہیڈ کوارٹر",
      koreaEntity: "ادارہ: سیال اینڈ ینگ اے ٹریڈنگ کمپنی",
      koreaDesc: "آٹوموٹو اور ہیوی مشینری پارٹس بنانے والے سرفہرست اداروں کے ساتھ B2B نیٹ ورک کا مربوط نظام۔ ہم کورین پروڈکشن لائنوں سے براہ راست تھوک قیمت پر حقیقی اسپیئر پارٹس (ہنڈائی، کیا اور تجارتی بیڑے کے لیے) عالمی منڈیوں میں بغیر کسی درمیانی فیس کے برآمد کرنے میں مہارت رکھتے ہیں۔",
      chinaTitle: "انڈسٹریل ہارڈویئر کا بنیادی مرکز",
      chinaEntity: "ادارہ: ییوو سیال انٹرنیشنل ٹریڈنگ کمپنی لمیٹڈ",
      chinaDesc: "بڑے پیمانے پر صنعتی خریداری اور انفراسٹرکچر لاجسٹکس نیٹ ورک کا انتظام۔ یہ مرکز تمام تعمیراتی سائٹس کے لیے انڈسٹریل ہارڈویئر، ہیوی ڈیوٹی پاور ٹولز، اور تعمیراتی آلات کی براہ راست سورسنگ فراہم کرتا ہے، جو افریقہ اور جی سی سی میں براہ راست شپمنٹ کے لیے بہترین ہے۔",
      whyChooseTitle: "عالمی شراکت دار سیال گروپ کا انتخاب کیوں کرتے ہیں؟",
      whyChoose1Title: "براہ راست فیکٹری قیمتیں",
      whyChoose1Desc: "تھرڈ پارٹی تجارتی بروکرز کے مارجن اور چھپی ہوئی فیسوں کا 100٪ خاتمہ۔",
      whyChoose2Title: "سخت کوالٹی کنٹرول",
      whyChoose2Desc: "کوالٹی کنٹرول اور شپمنٹ سے پہلے کا معائنہ براہ راست فیکٹری کی سطح پر کیا جاتا ہے۔",
      whyChoose3Title: "سپلائی چین کی بہترین لچک",
      whyChoose3Desc: "مضبوط کارپوریٹ گورننس کے تحت چلنے والی لاجسٹکس اور محفوظ عالمی تقسیم کے نیٹ ورکس۔",
      whyChoose4Title: "B2B تجارت میں 18+ سال کا تجربہ",
      whyChoose4Desc: "سرحد پار تجارتی مذاکرات، بین الاقوامی خریداری کی عمدگی، اور سپلائی چین مینجمنٹ میں دہائیوں کا تجربہ۔",
      ceoMessageTitle: "ہمارے گروپ سی ای او کا پیغام",
      ceoSubtitle: "محمد امجد: سپلائی چین کی مضبوطی کی ایک میراث",
      ceoDesc1: "محمد امجد کی قیادت میں، سیال گروپ نے تقریباً دو دہائیوں کے دوران ایک مقامی تجارتی ایجنٹ سے ملٹی جورسڈکشنل صنعتی قوت کا سفر طے کیا ہے۔ جنوبی کوریا اور چین سے جی سی سی اور افریقہ تک براہ راست فیکٹری پائپ لائنیں اور شپنگ روٹس قائم کر کے، انہوں نے سپلائی چین کی آزادی کا ایک نیا معیار قائم کیا ہے۔",
      ceoDesc2: "ان کی اسٹریٹجک توجہ علاقائی قوانین (جیسے سعودی عرب میں SASO، عمان میں OPAL، اور موزمبیق میں کسٹمز آپریشنز) کی مکمل پاسداری کے ساتھ B2B لاجسٹکس کے معاہدوں پر ہے، جو ہمارے کاروباری شراکت داروں کے لیے براہ راست قیمت کے فوائد کی ضمانت دیتے ہیں۔",
      ceoConsultation: "B2B مشاورت کا وقت طے کریں",
      divisionsTitle: "ہمارے کاروباری شعبے",
      divisionsSubtitle: "جی سی سی، افریقہ اور مشرقی ایشیا میں ترقی اور استحکام کو فروغ دینے والے ہمارے مربوط شعبوں کو دیکھیں۔",
      machineryTitle: "ہیوی مشینری ڈویژن",
      machineryDesc: "عمان (ایس کے ٹرانسپورٹس)، سعودی عرب (سیال انٹرنیشنل کمپنی)، اور پاکستان میں کرینوں کی فروخت، کرایہ اور اسپیئر پارٹس کی تقسیم۔",
      partsTitle: "گاڑیوں کے اسپیئر پارٹس",
      partsDesc: "ہنڈائی اور کیا گاڑیوں کے حقیقی اور متبادل اسپیئر پارٹس کی بڑے پیمانے پر فراہمی، جو جنوبی کوریا اور چین کے نیٹ ورکس سے براہ راست حاصل کیے جاتے ہیں۔",
      hardwareTitle: "انڈسٹریل ہارڈویئر",
      hardwareDesc: "موزمبیق میں انفراسٹرکچر کی ترقی کے لیے تقسیم کا نظام، جو ہمارے چین کے مراکز سے براہ راست حاصل کردہ معیاری تعمیراتی مواد فراہم کرتا ہے۔",
      stats1: "سالہ میراث",
      stats2: "عالمی مراکز",
      stats3: "بیچ کا منافع",
      stats4: "معائنہ شدہ معیار",
    },
    about: {
      whoWeAre: "ہم کون ہیں",
      title: "18 سالہ کثیر القومی گورننس",
      desc: "تقریباً دو دہائیوں سے، سیال گروپ ملٹی جورسڈکشنل گورننس اور سرحد پار سپلائی چین کو بہتر بنانے میں ایک پیش پیش رہا ہے۔ جنوبی کوریا، چین، عمان، سعودی عرب اور مشرقی افریقہ میں فعال مراکز کے ساتھ اسٹریٹجک طور پر قائم، ہمارے آپریشنز دنیا کے بڑے صنعتی مراکز کو ابھرتی ہوئی منڈیوں سے جوڑتے ہیں۔ سی ای او محمد امجد کی تجارتی قوانین کی پاسداری، اعلیٰ سطحی سفارتی مذاکرات، اور فیکٹری ڈائریکٹ خریداری کے عزم کی بدولت، گروپ ہیوی لفٹنگ مشینری کی فروخت اور کرائے، کیا اور ہنڈائی کے حقیقی پارٹس، اور صنعتی ہارڈویئر کی بلک فراہمی میں بہترین کارکردگی کا ضامن ہے۔ ہمارا کارپوریٹ گورننس فریم ورک بغیر کسی رکاوٹ کے بین الاقوامی قوانین کی تعمیل کی ضمانت دیتا ہے، جس سے دنیا بھر میں علاقائی تقسیم کاروں اور سرکاری و نجی اداروں کے ساتھ مضبوط شراکت داری قائم ہوئی ہے۔",
      ceoProfileTitle: "ایگزیکٹو لیڈرشپ پروفائل",
      ceoProfileHeading: "محمد امجد: سپلائی چین کا ایک وژنری خواب",
      ceoQuote: "لچک صرف سپلائی چین کے بحرانوں سے بچنا نہیں ہے؛ بلکہ ایسے براہ راست راستے بنانا ہے کہ ہمارے شراکت داروں کا کام کبھی نہ رکے۔",
      ceoDelegate: "🏛️ جی سی سی اور مشرقی ایشیا تجارتی نمائندہ",
      ceoDesc1: "گروپ سی ای او اور بانی محمد امجد نے سرحد پار براہ راست اور اعلیٰ ترین کاروباری تعلقات قائم کرنے کے ہدف کے ساتھ سیال گروپ کی بنیاد رکھی۔ شروع میں ہی یہ جان کر کہ درمیانی بروکرز کا مارجن سپلائی چین کی کارکردگی کو کم کرتا ہے، انہوں نے فیکٹری ڈائریکٹ سورسنگ نیٹ ورکس بنانے میں تقریباً دو دہائیاں لگائیں۔",
      ceoDesc2: "ان کا بین الاقوامی تجارتی مذاکرات کا تجربہ ایک مضبوط قانونی اور گورننس فریم ورک پر مبنی ہے۔ ان کے آپریشنز متعدد ممالک میں پھیلے ہوئے ہیں، جس کی وجہ سے سیال گروپ جنوبی کوریا، چین، جی سی سی (عمان اور سعودی عرب)، اور افریقہ (موزمبیق) میں کسٹمز قوانین اور تجارتی شرائط پر کامیابی سے عمل درآمد کرتا ہے۔",
      ceoDesc3: "ان کاموں کو سنبھالنے اور صارفین تک بروقت فراہمی کو یقینی بنانے کے لیے، سیال گروپ مخصوص آن لائن پلیٹ فارمز چلاتا ہے، بشمول ہیوی مشینری بیڑے کے لیے 'SK Transports Oman'، اور گاڑیوں کے پرزوں کی سورسنگ اور سروسز کے لیے 'Sial Kingdom' اور 'Yahya Auto Parts'۔",
      focusAreas: "توجہ کے شعبے",
      focusValue: "سرحد پار ٹیرف اور کسٹمز قوانین کی تعمیل",
      strategicHubs: "اسٹریٹجک مراکز",
      strategicValue: "سیول، ییوو، مسقط، جدہ",
      pillarsTitle: "ادارے کا بنیادی مرکز",
      pillarsHeading: "کارپوریٹ صلاحیتیں",
      pillar1Title: "عالمی سپلائی چین کی لچک",
      pillar1Desc: "چین اور کوریا میں سورسنگ مراکز کی براہ راست ملکیت برقرار رکھ کر، سیال گروپ اسٹاک کی دستیابی کی ضمانت دیتا ہے اور صارفین کو سمندری رکاوٹوں اور جغرافیائی سیاسی سپلائی کے جھٹکوں سے محفوظ رکھتا ہے۔",
      pillar2Title: "تجارتی مذاکرات کی مہارت",
      pillar2Desc: "ہمارے سی ای او کے بین الاقوامی پورٹ حکام اور شپنگ لائنوں کے ساتھ براہ راست تعلقات کسٹمز کی تیز رفتار منظوری اور انتہائی مناسب کرایوں کو یقینی بناتے ہیں۔",
      pillar3Title: "ملٹی جورسڈکشنل گورننس",
      pillar3Desc: "علاقائی کارپوریٹ قوانین کی سخت تعمیل، بشمول سعودی عرب میں SASO، عمان میں OPAL، اور موزمبیق اور جنوبی ایشیا میں کسٹمز کلیئرنس کے پروٹوکول۔",
      networkTitle: "کارپوریٹ نیٹ ورک",
      networkHeading: "ہمارا عالمی کارپوریٹ نیٹ ورک",
      networkDesc: "سیال گروپ متعدد بین الاقوامی ممالک میں کام کرتا ہے۔ ہمارے 10 رجسٹرڈ ذیلی اداروں، لاجسٹکس چینلز، اور براہ راست سورسنگ مراکز کو فلٹر کریں۔",
    },
    machinery: {
      titleBadge: "ڈویژن پروفائلنگ",
      heading: "ہیوی مشینری اور بیڑے کی لاجسٹکس",
      subtitle: "ہیوی لفٹ موبائل کرینیں، تعمیراتی گاڑیاں، اور ہیوی ڈیوٹی اسپیئر پارٹس فراہم کرنا۔ ہمارا شعبہ سخت کوالٹی کنٹرول کے تحت تین اہم علاقائی مراکز میں کام کرتا ہے۔",
      omanBadge: "🇴🇲 عمان کے آپریشنز",
      omanTitle: "موبائل کرین کی فروخت اور کرائے میں جی سی سی کی قیادت",
      omanDesc: "ایک دہائی سے زیادہ عرصے سے، ایس کے ٹرانسپورٹس عمان (SK Transports Oman) سلطنت عمان میں ہیوی لفٹنگ کے لیے ایک بہترین برانڈ رہا ہے۔ کثیر صلاحیت والی موبائل کرینوں اور کرالر کرینوں میں مہارت حاصل کر کے، ہم تیل اور گیس کی بڑی پائپ لائنوں، سمندری کارگو اور شہری بنیادی ڈھانچے کے منصوبوں کی خدمت کرتے ہیں۔",
      omanFeature1: "✓ 25 سے 500 ٹن وزن اٹھانے کی صلاحیت",
      omanFeature2: "✓ OPAL سے تصدیق شدہ آپریٹرز",
      omanFeature3: "✓ 24/7 سائٹ سپورٹ اور سروس",
      omanCta: "ایس کے ٹرانسپورٹس عمان سائٹ دیکھیں ↗",
      fleetTitle: "فعال بیڑے کے پورٹ فولیو کا مظاہرہ",
      fleetBadge: "PDO سے منظور شدہ کرینیں",
      saBadge: "🇸🇦 سعودی عرب میں توسیع",
      saTitle: "نئی لانچ شدہ رینٹل کرینیں اور ہیوی اسپیئر پارٹس",
      saDesc: "جدہ اور مشرقی صوبے میں سیال کا نیٹ ورک بڑھانا تاکہ سعودی وژن 2030 کے منصوبوں کو سپورٹ فراہم کی جا سکے۔ سیال انٹرنیشنل کمپنی موبائل کرینوں کی فروخت، طویل مدتی کرائے، اور اعلیٰ معیار کے ہیوی اسپیئر پارٹس کی تقسیم پیش کرتی ہے۔",
      saFeature1: "جنوبی کوریا کے نیٹ ورکس سے براہ راست پارٹس کی تبدیلی",
      saFeature2: "موبائل کرین کی دیکھ بھال اور رگنگ کی خدمات",
      saFeature3: "SASO اور سعودی آئل فیلڈ سیفٹی معیارات کی تعمیل",
      saCta: "سعودی عرب کے لیے کوٹیشن کی درخواست کریں",
      pkBadge: "🇵🇰 پاکستان آپریشنز",
      pkTitle: "مشرقی ایشیائی سورسنگ مرکز اور علاقائی درآمدات",
      pkDesc: "بہترین تعمیراتی مشینری اور جدید زرعی آلات کی بڑے پیمانے پر درآمد اور تقسیم۔ درمیانے بروکرز کا مارجن ختم کر کے، ہم پاکستان کے ٹھیکیداروں اور کاشتکاروں کو براہ راست ہیوی مشینری فراہم کرتے ہیں۔",
      pkFeature1: "کرالر ٹریکٹرز اور ہارویسٹ لوڈرز",
      pkFeature2: "جدید زرعی بیج بونے والی مشینری",
      pkFeature3: "جنوبی کوریا اور چین کے سورسنگ مراکز سے براہ راست درآمد",
      pkCta: "پاکستان درآمدات کے بارے میں پوچھ گچھ کریں",
    },
    parts: {
      badge: "آٹوموٹو ڈویژن",
      heading: "گاڑیوں کے حقیقی اسپیئر پارٹس",
      subtitle: "کوریائی مسافر اور تجارتی گاڑیوں کے لیے نئے اور پرانے حقیقی اسپیئر پارٹس کی بڑے پیمانے پر تقسیم۔ مینوفیکچررز اور تصدیق شدہ برآمد کنندگان کے ساتھ براہ راست مربوط نیٹ ورک۔",
      specBadge: "بنیادی مہارت",
      specHeading: "ہنڈائی اور کیا پارٹس کی بے مثال فراہمی",
      specDesc: "ہم تمام مشہور ہنڈائی اور کیا ماڈلز کے نئے اور پرانے حقیقی اسپیئر پارٹس کی فراہمی میں مہارت رکھتے ہیں۔ ہمارا تقسیم کا نظام جی سی سی کے بڑے گوداموں، تجارتی گاڑیوں کے مالکان اور ریٹیل زنجیروں کی ضروریات کو پورا کرتا ہے۔ براہ راست فیکٹریوں سے خریداری کی وجہ سے قیمتیں انتہائی مناسب ہیں۔",
      cat1Title: "انجن اور ٹرانسمیشن",
      cat1Desc: "مکمل انجن، گیئر باکسز، پسٹن، اور دیگر اہم پارٹس۔",
      cat2Title: "سسپنشن اور اسٹیرنگ",
      cat2Desc: "شاک ابزاربرز، کنٹرول آرمز، اور اسٹیرنگ ریکس۔",
      cat3Title: "الیکٹریکل اور باڈی پینلز",
      cat3Desc: "الٹرنیٹرز، ای سی یو (ECU) کمپیوٹر، ہیڈ لیمپ، اور بمپرز۔",
      cat4Title: "جلد گھسنے والے پارٹس",
      cat4Desc: "بریک پیڈز، فلٹر اور گسکیٹ۔",
      infraHeading: "جی سی سی کا تقسیم کا بنیادی ڈھانچہ",
      infraOmanTitle: "عمان کا مرکز (سیال کنگڈم ٹریڈنگ کمپنی)",
      infraOmanDesc: "مسقط (سیب) میں قائم سیال کنگڈم ٹریڈنگ کمپنی سلطنت عمان میں ہمارے بیڑے اور گاڑیوں کے اصل اسپیئر پارٹس کی تیز رفتار فراہمی اور تقسیم کو یقینی بناتی ہے۔",
      infraSaTitle: "سعودی عرب میں توسیع",
      infraSaDesc: "عمان کے کامیاب نظام کی طرز پر، اب ہمارے جدہ کے مراکز سے سعودی عرب کے تمام بڑے تجارتی مراکز میں گاڑیوں کے پارٹس فراہم کیے جا رہے ہیں۔",
      hubsBadge: "گاہکوں کے فعال پلیٹ فارمز",
      hubsHeading: "گاڑیوں کے اسپیئر پارٹس اور سروس مراکز",
      hubsDesc: "سیال گروپ عمان میں دو مشہور کسٹمر برانڈز چلاتا ہے، جو فیکٹری ریٹ پر پارٹس اور ماہرانہ مرمت کی خدمات فراہم کرتے ہیں۔",
      skBadge: "عمان السیب ڈویژن",
      skTitle: "سیال کنگڈم ٹریڈنگ کمپنی",
      skDesc: "سیال کنگڈم معبیلہ صنعتی علاقے (السیب، عمان) میں گاڑیوں کی مرمت اور حقیقی اسپیئر پارٹس کا ایک قابل اعتماد مرکز ہے۔ یہ کیا اور ہنڈائی گاڑیوں کی سروسز اور فیکٹری ریٹ پر پارٹس کی تبدیلی فراہم کرتا ہے۔",
      skCta: "سیال کنگڈم کی ویب سائٹ دیکھیں ↗",
      yahyaBadge: "عالمی لاجسٹکس مرکز",
      yahyaTitle: "یحییٰ آٹو پارٹس",
      yahyaDesc: "2006 میں قائم ہونے والا یحییٰ آٹو پارٹس (یحییٰ بن خلفان کمپنی) عمان میں ہنڈائی، کیا اور جینیسس کے اسپیئر پارٹس کا ایک اہم تھوک تقسیم کار ہے، جس کے آپریشنز جنوبی کوریا اور چین میں پھیلے ہیں۔",
      yahyaCta: "یحییٰ آٹو پارٹس کی ویب سائٹ دیکھیں ↗",
      integrityHeading: "براہ راست فیکٹری سورسنگ کی سچائی",
      integrityDesc: "ہمارے سورسنگ دفاتر کے ذریعے فیکٹری سے گاہک تک بہترین کوالٹی اور مناسب ریٹ کی ضمانت۔",
      sourcingKorea: "سیول، جنوبی کوریا میں قائم ہمارا سورسنگ آفس مینوفیکچررز سے براہ راست نئے پارٹس حاصل کرتا ہے، اور پرانے انجن و پارٹس کی پیکنگ سے پہلے خود معائنہ کرتا ہے۔",
      sourcingChina: "چین کے شہر ییوو (Yiwu) میں قائم ہمارا مرکز متبادل صنعتی پارٹس کی کوالٹی چیک کرتا ہے اور انہیں محفوظ طریقے سے برآمد کرتا ہے۔",
      erpTitle: "ریئل ٹائم ERP ٹریکنگ",
      erpDesc: "جدید Odoo ERP سسٹم کے ذریعے گوداموں، فیکٹری آرڈرز اور کسٹمز کلیئرنس کی صورتحال پر نظر رکھنا۔",
    },
    hardware: {
      badge: "صنعتی شعبہ",
      heading: "انڈسٹریل ہارڈویئر اور تعمیراتی مواد",
      subtitle: "اعلیٰ طاقت والے لوہے اور تعمیراتی سامان کی درآمد اور تقسیم۔ مشرقی افریقہ میں بنیادی ڈھانچے کے بڑے منصوبوں کو براہ راست فیکٹریوں سے ملانا۔",
      mzBadge: "🇲🇿 افریقہ پائپ لائنز",
      mzTitle: "موزمبیق کے اسٹریٹجک انفراسٹرکچر منصوبوں کی سپورٹ",
      mzDesc: "چونکہ موزمبیق میں کان کنی اور ٹرانسپورٹ کے شعبوں میں بڑے پیمانے پر کام ہو رہا ہے، سیال گروپ وہاں تعمیراتی سامان کی فراہمی میں اہم کردار ادا کر رہا ہے۔ ہم بلک میں انڈسٹریل ہارڈویئر، سریا، اور حفاظتی سامان فراہم کرتے ہیں۔ Maputo اور Beira بندرگاہوں پر ہمارے کسٹمز ایجنٹس سارا کام سنبھالتے ہیں۔",
      cat1Title: "ساختی مواد",
      cat1Desc: "کنسٹرکشن سریا، لوہے کے گارڈرز، اور لوہے کی جالی۔",
      cat2Title: "بولٹس اور رسی",
      cat2Desc: "اعلیٰ طاقت والے بولٹس، کرین کی اسٹیل رسیاں اور کلیمپ۔",
      cat3Title: "حفاظتی سامان اور پائپنگ",
      cat3Desc: "اسٹیل کے پائپ، والوز، کٹس اور صنعتی اوزار۔",
      integrityTitle: "سپلائی کی صورتحال",
      routeTitle: "شپنگ کا راستہ:",
      routeVal: "Ningbo ➔ Maputo بندرگاہ",
      clearTitle: "کسٹمز کلیئرنس کا وقت:",
      clearVal: "7 دنوں سے کم",
      qualityTitle: "معیار کی یقین دہانی:",
      qualityVal: "100٪ مصدقہ",
      reachTitle: "تقسیم کا دائرہ کار:",
      reachVal: "Maputo، Beira، Nacala",
      procBadge: "خریداری کی عمدگی",
      procHeading: "چین کے ییوو مرکز کے ساتھ مربوط نظام",
      procTitle: "چین کا خریداری مرکز",
      proc1Title: "براہ راست فیکٹری تعلقات",
      proc1Desc: "چین کی بڑی اسٹیل ملوں اور فیکٹریوں کے ساتھ براہ راست شراکت داری۔",
      proc2Title: "بلک قیمت کا فائدہ",
      proc2Desc: "براہ راست فیکٹری سے بڑی مقدار میں خریداری بیچ کے بروکرز کے کمیشن ختم کرتی ہے۔",
      proc3Title: "اپنی مرضی کے مطابق کٹائی",
      proc3Desc: "لوہے کے گارڈرز کو کسٹمر کے ڈیزائن کے مطابق فیکٹری میں کاٹنے اور تیار کرنے کی سہولت۔",
      procDesc: "چین میں قائم ہمارا دفتر سامان کی لوڈنگ اور ٹیسٹنگ کی نگرانی کرتا ہے۔ ہم روانگی سے پہلے لوہے کی موٹائی اور مضبوطی کی جانچ کرتے ہیں تاکہ ناقص مال سے بچا جا سکے۔",
      cta: "بلک مٹیریل RFQ جمع کریں",
    },
    contact: {
      badge: "انکوائری ڈیسک",
      heading: "کارپوریٹ رابطے جمع کرنے کا نظام",
      desc: "ہمارے کسی بھی شعبے سے رابطہ کریں۔ اپنی مطلوبہ مارکیٹ یا ڈویژن کا انتخاب کریں تاکہ آپ کی انکوائری براہ راست متعلقہ دفتر کو بھیجی جا سکے۔",
      formTitle: "B2B انکوائری جمع کرنے کا پورٹل",
      formDesc: "رابطہ کرنے کے لیے متعلقہ شعبہ اور مرکز منتخب کریں تاکہ کام جلد از جلد شروع کیا جا سکے۔",
      companyName: "کمپنی کا نام",
      contactName: "رابطہ کار کا نام",
      email: "کمپنی کا ای میل ایڈریس",
      phone: "فون نمبر (ملک کا کوڈ شامل کریں)",
      division: "مطلوبہ شعبہ",
      selectDiv: "شعبہ منتخب کریں",
      destHub: "منزل کا آپریشنز ہب",
      selectHub: "آپریشنز ہب منتخب کریں",
      details: "انکوائری اور کوٹیشن کی تفصیلات",
      placeholderDetails: "براہ کرم سائز، تعداد، منزل اور فراہمی کی تاریخ وغیرہ درج کریں...",
      submitting: "انکوائری بھیجی جا رہی ہے...",
      submit: "B2B انکوائری جمع کریں",
      successTitle: "انکوائری کامیابی سے موصول ہو گئی",
      successDesc: "آپ کی تفصیلات درج کر لی گئی ہیں اور متعلقہ دفتر کو بھیج دی گئی ہیں۔ ہمارا نمائندہ جلد ہی آپ سے رابطہ کرے گا۔",
      errTitle: "فارم جمع کرنے میں غلطی",
      errDesc: "آپ کا فارم جمع نہیں ہو سکا۔ براہ کرم انٹرنیٹ کنکشن چیک کر کے دوبارہ کوشش کریں۔",
      infoTitle: "کارپوریٹ پتے",
      hqTitle: "عالمی ہیڈ کوارٹر",
      hqVal: "مسقط، سلطنت عمان",
      emailTitle: "مرکزی ای میل ایڈریس",
      wechatTitle: "WeChat کارپوریٹ آئی ڈی",
      workTitle: "رسمی دفتری اوقات",
      workVal: "08:00 - 17:00 (GMT+4) | پیر - جمعہ",
    }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  // Load language preference on mount
  useEffect(() => {
    const saved = localStorage.getItem("sial-language") as Language;
    if (saved && ["en", "ar", "zh", "ko", "ur"].includes(saved)) {
      setLanguageState(saved);
      const dir = saved === "ar" || saved === "ur" ? "rtl" : "ltr";
      document.documentElement.dir = dir;
      document.documentElement.lang = saved;
    } else {
      // Check for legacy googtrans cookie just in case, to migrate settings
      const getCookie = (name: string) => {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop()?.split(";").shift();
        return null;
      };
      const transCookie = getCookie("googtrans");
      if (transCookie) {
        const lang = transCookie.split("/").pop();
        if (lang) {
          let matched: Language = "en";
          if (lang === "zh-CN" || lang === "zh") matched = "zh";
          else if (["en", "ar", "ko", "ur"].includes(lang)) matched = lang as Language;
          
          setLanguageState(matched);
          const dir = matched === "ar" || matched === "ur" ? "rtl" : "ltr";
          document.documentElement.dir = dir;
          document.documentElement.lang = matched;
          localStorage.setItem("sial-language", matched);
        }
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("sial-language", lang);
    const dir = lang === "ar" || lang === "ur" ? "rtl" : "ltr";
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  };

  const dir = language === "ar" || language === "ur" ? "rtl" : "ltr";

  // Nested translation lookup helper
  const t = (key: string): string => {
    const keys = key.split(".");
    let current: any = translations[language] || translations["en"];
    for (const k of keys) {
      if (current && current[k] !== undefined) {
        current = current[k];
      } else {
        // Fallback to English translation
        let fallback = translations["en"];
        for (const fk of keys) {
          if (fallback && fallback[fk] !== undefined) {
            fallback = fallback[fk];
          } else {
            return key; // return key if fallback not found
          }
        }
        return fallback;
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      <div dir={dir} className={dir}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
